const{chromium}=require('playwright'),assert=require('node:assert/strict');
const base='http://localhost:8000/listening/day-3/',api='http://127.0.0.1:8788';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[];async function client(){const c=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});await c.route('**/shared/classroom/config.js',r=>r.fulfill({contentType:'application/javascript',body:`export const serviceURL='${api}';`}));await c.route('**/release-config.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('serviceReady=false','serviceReady=true')});});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));return p;}
const teacher=await client(),a=await client(),b=await client();await teacher.goto(base+'teacher-control/');await teacher.locator('#create-class').click();await teacher.locator('#teacher-session').waitFor();const code=(await teacher.locator('#classroom-code').innerText()).trim();
for(const p of[a,b]){await p.goto(base);assert.equal(await p.locator('section.activity').count(),16);await p.locator('#class-code').fill(code);await p.locator('#class-connect-form button').click();await p.getByText('Connected ✓',{exact:true}).waitFor();await p.locator('#l31-1').fill('hypothesis');assert.equal(await p.locator('textarea').count(),0);await p.locator('[data-activity="l31"]').evaluate(f=>f.requestSubmit());assert.equal(await p.locator('#l31 .result').innerText(),'');assert.equal(await p.locator('.source-extract').count(),0);assert(!(await p.locator('main').innerText()).includes('Yeah, that’s dope.'));assert.equal(await p.locator('form[data-activity] input:disabled,form[data-activity] textarea:disabled').count(),0);}
await teacher.locator('[data-release="l31"]').click();for(const p of[a,b]){await p.locator('[data-answer-check="l31"]').waitFor();assert.equal(await p.locator('#l31-1').inputValue(),'hypothesis');assert(!await p.locator('[data-answer-check="l34"]').isVisible());}
await a.context().setOffline(true);await a.locator('#checkpoint1-5').fill('furnished');await teacher.locator('[data-release="l34"]').click();await b.locator('[data-answer-check="l34"]').waitFor();await a.context().setOffline(false);await a.locator('[data-answer-check="l34"]').waitFor();assert.equal(await a.locator('#checkpoint1-5').inputValue(),'furnished');
await teacher.locator('#release-all').click();await a.locator('[data-answer-check="spell31"]').waitFor();assert.equal(await a.locator('#phrases34 .source-extract').count(),0);
const keys={checkpoint2:['F','B','D','A'],l31:['hypothesis','evidence','methodology','variable','analyze','significant','outcome','implication','evaluate'],spell31:['B','D','A','C','B','D','A','C','B'],l32:['3','1','2','5','4','8','6','7'],l33:['B','C','C','B'],l34:['A','C','A','B','B','D','E','peer review','citations','academic community'],phrases34:['A','B','A','B','A','B','A','B','A','A','B','A'],academic34:['B','A','A','B','B','A','A','B']};for(const[id,key]of Object.entries(keys)){const fields=a.locator(`#${id} form fieldset`);for(const[i,v]of key.entries()){const field=fields.nth(i);if(await field.locator('input[type=radio]').count())await field.locator(`input[value="${v}"]`).check();else await field.locator('input').fill(v);}await a.locator(`[data-answer-check="${id}"]`).click();assert((await a.locator(`#${id} .result`).innerText()).startsWith(`${key.length} / ${key.length}`));}
for(const [id,value] of Object.entries({'1':'Qahoor',course:'data',arrival:'28th','4':'9476 3812','5':'furnished','6':'850','7':'Victoria','8':'halal'}))await a.locator('#checkpoint1-'+id).fill(value);
await a.locator('[data-answer-check="checkpoint1"]').click();assert((await a.locator('#checkpoint1 .result').innerText()).startsWith('8 / 8'));assert((await a.locator('#checkpoint1').innerText()).includes('Marking pending'));
assert.equal(await a.locator('#l31 fieldset').count(),9);assert.equal(await teacher.locator('[data-release]').count(),10);
await a.locator('[data-answer-check="think31"]').click();assert(!(await a.locator('#think31 .result').innerText()).includes('/'));await a.locator('#think31 .model button').first().click();assert(await a.locator('#model-think31-0').isVisible());await a.locator('#think31 .model button').first().click();assert(!await a.locator('#model-think31-0').isVisible());
await a.locator('[data-answer-check="say34"]').click();assert(!await a.locator('#model-say34-11').isVisible());await a.locator('#say34 .model button').nth(11).click();assert((await a.locator('#model-say34-11').innerText()).includes('Biophysics lecture in 10'));assert.equal(await a.locator('#notice31 input,#notice31 button').count(),0);assert.equal(await a.locator('#yesterday').count(),0);assert.equal(await a.locator('#l34 .listening-rounds li').count(),3);await a.reload();await a.locator('#l34 .result').filter({hasText:'10 / 10'}).waitFor();assert.equal(await a.locator('#checkpoint1-5').inputValue(),'furnished');await b.reload();await b.getByText('Connected ✓',{exact:true}).waitFor();assert.equal(await b.locator('#l31-1').inputValue(),'hypothesis');
await a.locator('#l34-28').fill('the full peer review');await a.locator('[data-answer-check="l34"]').click();assert((await a.locator('#l34 .result').innerText()).startsWith('9 / 10'));await a.locator('#discussion [data-topic="2"]').click();assert.equal(await a.locator('.discussion-bank').innerText(),'');await a.reload();assert.equal(await a.locator('#discussion [aria-pressed=true]').innerText(),'No expressions');
assert.equal((await a.request.post(`${api}/v1/classes/${code}/release?workshop=listening-day-3`,{headers:{Authorization:'Bearer '+code},data:{all:true}})).status(),403);assert.equal((await a.request.get(`${api}/v1/classes/${code}?workshop=listening-day-2`)).status(),409);
await a.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode()})));for(const width of[360,390,430,1280]){await a.setViewportSize({width,height:900});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await a.locator('#l34').evaluate(e=>e.scrollIntoView({behavior:'instant'}));await a.screenshot({path:`/tmp/day3-${width}.png`});await teacher.setViewportSize({width,height:900});assert(await teacher.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}assert.equal(await a.locator('audio,video').count(),0);assert.deepEqual(errors,[]);await browser.close();console.log('PASS Day 3: 16 sections, nine spellings and nine guided spoken prompts, Manchester partial marking, 10 release controls, 3 isolated clients/local Worker, pre-release guard, model show/hide, notice-only review, two-listen instructions, simple Say It, word limit, offline catch-up, refresh, no support phase, 403/409, four responsive widths.');})().catch(e=>{console.error(e);process.exit(1)});
