import {activities} from './content.js';
import {workshop,stages,serviceReady} from './release-config.js';
import {ClassroomConnection,mountStudentConnection} from '../../shared/classroom/client.js';
const key='ielts-listening-day-3-v1';let state={responses:{},checked:{}};
try{const saved=JSON.parse(localStorage.getItem(key));if(saved?.responses&&saved?.checked)state=saved;}catch{}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normal=x=>String(x??'').trim().replace(/\s+/g,' ').toLowerCase();
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{document.querySelector('#storage-note').textContent='Saving is unavailable in this browser. Keep this page open to retain your responses.';}}
const release=new ClassroomConnection(workshop,stages),name=(a,q,i)=>`${a.id}-${q.storageId??q.number??i+1}`;
function question(a,q,i){const n=name(a,q,i),number=q.number??i+1;
 if(a.compactMap)return `<fieldset class="map-answer-row"><legend>${number}</legend><div class="map-letters">${q.options.map(o=>`<label><input type="radio" name="${n}" value="${o.value}"><span>${o.value}</span></label>`).join('')}</div><p class="feedback" data-feedback="${n}"></p></fieldset>`;
 let field=q.type==='spoken'?`${q.sentence?`<blockquote class="sentence-scaffold">${esc(q.sentence)}</blockquote>`:''}<p class="spoken-prompt">Say it aloud. Tell your partner.</p>${a.guided?`<div data-guided-model="${i}"></div>`:''}`:q.type==='reflection'?`<div data-spoken-reflection></div>`:q.type==='multi'?`<div class="options">${q.options.map(o=>`<label class="option"><input type="checkbox" name="${n}" value="${o.value}"><span>${esc(o.value)}. ${esc(o.text)}</span></label>`).join('')}</div>`:q.type==='open'?`<label class="visually-hidden" for="${n}">Your response</label><textarea class="response-text" id="${n}" name="${n}" rows="3"></textarea>`:q.type==='register'?`<div class="options">${['with friends','in a university peer discussion','in a presentation','in academic writing'].map((text,j)=>`<label class="option"><input type="checkbox" name="${n}" value="${j}"><span>${text}</span></label>`).join('')}</div>`:q.options?`<div class="options">${q.options.map(o=>`<label class="option"><input type="radio" name="${n}" value="${o.value}"><span>${esc(o.value)}. ${esc(o.text)}</span></label>`).join('')}</div>`:`<label class="visually-hidden" for="${n}">Your answer</label><input class="response-text" type="text" id="${n}" name="${n}" autocomplete="off" spellcheck="false">`;
 return `${q.group?`<p class="instruction">${esc(q.group)}</p>`:''}<fieldset class="choice-item"><legend>${number===''?'':number+'. '}${esc(q.label)}</legend><div data-extract="${i}"></div>${field}<p class="feedback" data-feedback="${n}"></p></fieldset>`;
}
document.querySelector('#navigation').innerHTML=activities.map(a=>`<a href="#${a.id}">${esc(a.title)}</a>`).join('');
document.querySelector('#activities').innerHTML=activities.map((a,i)=>`<section class="activity ${a.compactMap?'compact-map':''}" id="${a.id}"><p class="eyebrow">${esc(a.eyebrow)}</p><h2>${esc(a.title)}</h2>${a.image?`<figure class="anchor-image"><a href="assets/${a.image}" target="_blank" rel="noopener" aria-label="Open image at full size"><img src="assets/${a.image}" alt="${esc(a.imageAlt)}" loading="lazy"></a></figure>`:''}<p>${esc(a.instruction||'')}</p>${a.listens?`<ol class="listening-rounds">${a.listens.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:''}${a.notices?'<div data-notices></div>':''}${a.pending?`<p class="pending-source">Local draft · ${esc(a.pending)}</p>`:''}${a.bank?`<div class="word-bank" aria-label="Word box">${a.bank.map(w=>`<span>${esc(w)}</span>`).join('')}</div>`:''}${a.requires?'<p class="muted" data-source-wait>Listen first. Your teacher will release the original extracts for this review. You can still respond aloud.</p>':''}${a.compactMap?`<p class="muted map-help">On a phone, swipe the map sideways or tap it to open full size.</p><div class="map-key">${a.questions[0].options.map(o=>`<span><b>${o.value}</b> ${esc(o.text)}</span>`).join('')}</div>`:''}<form data-activity="${a.id}">${a.questions.map((q,j)=>question(a,q,j)).join('')}${a.ready!==false&&!a.independent?`<p class="muted" data-wait>Your teacher will release ${a.production?'model review':'answer checking'}. You can keep working.</p><button data-answer-check="${a.id}" type="submit" hidden disabled>${a.production?'Review possibilities':'Check & reflect'}</button>`:''}<p class="result" role="status"></p><div class="review-layer" hidden></div></form>${a.discussion?'<div class="discussion" id="discussion"></div>':''}<a class="next" href="#${activities[i+1]?.id||'intro'}">Continue →</a></section>`).join('');
function unlocked(a){return release.isOpen(a.releaseId||a.id)&&(!a.requires||(release.isOpen(a.requires)&&(!a.afterChecked||state.checked[a.requires])));}
function clear(a){const form=document.querySelector(`[data-activity="${a.id}"]`);form.querySelectorAll('.feedback').forEach(p=>{p.textContent='';p.classList.remove('correct');});form.querySelectorAll('[data-guided-model]').forEach(el=>el.replaceChildren());form.querySelector('.result').textContent='';const layer=form.querySelector('.review-layer');layer.innerHTML='';layer.hidden=true;}
function check(a){if(a.ready===false||!unlocked(a))return;const form=document.querySelector(`[data-activity="${a.id}"]`),layer=form.querySelector('.review-layer');
 if(!a.production){let score=0,total=0;a.questions.forEach((q,i)=>{if(q.answer==null){if(q.pendingMarking)form.querySelector(`[data-feedback="${name(a,q,i)}"]`).textContent=q.pendingMarking;return;}total++;const n=name(a,q,i),answer=state.responses[n],accepted=Array.isArray(q.answer)?q.answer:[q.answer];const right=accepted.some(v=>normal(v)===normal(answer))&&(!q.limit||normal(answer).split(' ').length<=q.limit);score+=Number(right);const output=form.querySelector(`[data-feedback="${n}"]`);output.classList.toggle('correct',right);output.textContent=right?(a.id==='spell31'?`Correct: ${q.options.find(o=>o.value===q.answer).text}.`:'Correct.'):`Review this one. Answer: ${q.options?q.answer+' — '+q.options.find(o=>o.value===q.answer).text:accepted[0]}.`;});form.querySelector('.result').textContent=`${score} / ${total} · Use the score to decide what needs another listen.`;}
 else form.querySelector('.result').textContent='Compare possibilities. Your response does not have to match a model.';
 layer.innerHTML=(a.models||[]).map((m,i)=>`<div class="model"><button class="secondary" type="button" aria-expanded="false" aria-controls="model-${a.id}-${i}">${esc(a.questions[i]?.modelLabel||a.modelLabel||'One possibility')} · ${i+1}</button><p id="model-${a.id}-${i}" hidden>${esc(m)}<br>Try again. Use this expression if it fits what you want to say.</p></div>`).join('')+(a.reflection?`<p>${esc(a.reflection)}</p>`:'');
 layer.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{const p=document.getElementById(button.getAttribute('aria-controls'));p.hidden=!p.hidden;button.setAttribute('aria-expanded',String(!p.hidden));button.textContent=p.hidden?(a.modelLabel||'One possibility'):'Hide & try again';}));if(a.guided){layer.querySelectorAll('.model').forEach((model,i)=>{model.querySelector('button').textContent='I’ve said it — reveal';form.querySelector(`[data-guided-model="${i}"]`).replaceChildren(model);});}layer.hidden=!layer.innerHTML;state.checked[a.id]=true;save();refreshSources();
}
for(const a of activities){const form=document.querySelector(`[data-activity="${a.id}"]`);form.querySelectorAll('input,textarea').forEach(input=>{const value=state.responses[input.name];if(input.type==='checkbox')input.checked=Array.isArray(value)&&value.includes(input.value);else if(input.type==='radio')input.checked=value===input.value;else input.value=value??'';});form.addEventListener('input',event=>{const input=event.target;if(!input.name)return;state.responses[input.name]=input.type==='checkbox'?[...form.querySelectorAll('input[type=checkbox]')].filter(e=>e.name===input.name&&e.checked).map(e=>e.value):input.value;state.checked[a.id]=false;clear(a);save();refreshSources();});form.addEventListener('submit',event=>{event.preventDefault();check(a);});}
function sync(){for(const a of activities){const section=document.getElementById(a.id),button=section.querySelector('[data-answer-check]');if(button){const open=unlocked(a);button.hidden=!open;button.disabled=!open;section.querySelector('[data-wait]').hidden=open;if(!open)clear(a);else if(state.checked[a.id])check(a);}
 }refreshSources();renderReflection();renderDiscussionBank();}
function refreshSources(){for(const a of activities.filter(a=>a.requires)){const section=document.getElementById(a.id),ready=release.isOpen(a.requires)&&(!a.afterChecked||state.checked[a.requires]);section.querySelector('[data-source-wait]').hidden=ready;section.querySelectorAll('[data-extract]').forEach(el=>{const quote=a.extracts?.[Number(el.dataset.extract)];el.innerHTML=ready&&quote?`<blockquote class="source-extract">${esc(quote)}</blockquote>`:'';});const notices=section.querySelector('[data-notices]');if(notices)notices.innerHTML=ready?a.notices.map(([quote,meaning])=>`<blockquote class="source-extract">${esc(quote)}<p class="muted">${esc(meaning)}</p></blockquote>`).join(''):'';const button=section.querySelector('[data-answer-check]');if(button){const open=unlocked(a);button.hidden=!open;button.disabled=!open;section.querySelector('[data-wait]').hidden=open;if(!open)clear(a);}}}
function renderReflection(){const root=document.querySelector('[data-spoken-reflection]');if(!root)return;const labels=release.isOpen('language34')&&release.isOpen('l34')&&state.checked.l34?['Got it.','Gotcha.','That makes sense.','Actually, that reminds me…','I came across something similar…','Exactly what I was thinking.','I’m really on board with that.','Another expression','None yet']:['I supported an idea','I challenged an idea','I showed understanding','I connected ideas','I qualified a point','None yet'];root.innerHTML=labels.map(label=>`<label class="option"><input type="checkbox" name="transfer-reflection" value="${esc(label)}" ${(state.responses['transfer-reflection']||[]).includes(label)?'checked':''}><span>${esc(label)}</span></label>`).join('');}
const topics=[['Some support','Should students be allowed to use phones during lessons? Agree on two classroom rules.'],['Less support','Should everyone in a group project receive the same mark? Give reasons and find a compromise.'],['No expressions','Should a university provide recordings of every lecture? Discuss one benefit, one concern and a decision.']];
let discussionStage=Number(state.discussionStage)||0;
const discussion=document.querySelector('#discussion');discussion.innerHTML=`<p>Take about four minutes per discussion. Choose the amount of support you want; you can move in either direction.</p><div class="actions">${topics.map((t,i)=>`<button type="button" class="secondary" data-topic="${i}">${t[0]}</button>`).join('')}</div><p class="topic"></p><div class="discussion-bank"></div>`;
function renderDiscussionBank(){discussion.querySelector('.topic').textContent=topics[discussionStage][1];discussion.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.topic)===discussionStage)));discussion.querySelector('.discussion-bank').innerHTML=discussionStage===0&&release.isOpen('language34')&&release.isOpen('l34')&&state.checked.l34?'<p>Try a useful move if it fits: “I’m not sure about that.” · “They can be useful, but…” · “That makes sense.” · “I’m really on board with that.”</p>':discussionStage===1?'<p>Support an idea → challenge politely → connect to something you’ve encountered → partly agree → identify a limitation → suggest an alternative.</p>':'';}
discussion.addEventListener('click',e=>{if(e.target.dataset.topic!==undefined){discussionStage=Number(e.target.dataset.topic);state.discussionStage=discussionStage;save();renderDiscussionBank();}});renderDiscussionBank();
release.subscribe(sync);sync();const panel=mountStudentConnection(release,document.querySelector('#activities'));if(!serviceReady){panel.querySelectorAll('input,button').forEach(e=>e.disabled=true);panel.querySelector('#class-status').textContent='Local draft: Day 3 classroom activation is pending. You can keep working.';}
if(matchMedia('(max-width:850px)').matches)document.querySelector('#workshop-menu').open=false;document.querySelector('#navigation').addEventListener('click',e=>{if(e.target.closest('a')&&matchMedia('(max-width:850px)').matches)document.querySelector('#workshop-menu').open=false;});
