export const task2Content = {
  id: "writing-task-2-v0-1",
  title: "IELTS Writing Task 2",
  canonicalQuestion: "Some people believe that university education should be free for everyone. To what extent do you agree or disagree?",
  transferQuestion: "In many workplaces, employees can now work from home for some or all of the week. What are the advantages and disadvantages of this arrangement?",
  orderPolicy: {
    principle: "Randomise choices unless order is part of the meaning.",
    semanticOrderExceptions: {
      "workshop-units": "The learning sequence is cumulative.",
      "u3-judgement-scale": "Yes → Partly → No is an ordered scale.",
      "u6-learning-sequence": "Topic → job → introduction is a teaching sequence.",
      "b1-classification-scale": "The categories move from direct contribution to topic-only relevance.",
      "b3-position-scale": "Agreement choices form an ordered continuum.",
      "b4-development-scale": "Strong → could work → weak is an ordered scale.",
      "b6-aes-sequence": "Answer → Explain → Support is the taught checking sequence.",
      "w2-plan-scale": "The plan judgements form an ordered quality scale.",
      "w5-plan-fields": "The plan follows task → position → body contributions.",
      "w7-review-sequence": "The prompts and Yes → Partly → Not yet scale support an ordered structural review.",
      "c1-paragraph-sequence": "The paragraphs must remain in essay order.",
      "c4-before-after": "Original must precede revised writing for comparison.",
      "c4-criteria-sequence": "The teaching lenses retain the official criteria sequence.",
      "c6-process-sequence": "Read → plan → build → write → check → revise is the process being learned.",
    },
  },
  sections: [
    { id: "understand", label: "Understand the question", shortLabel: "Understand" },
    { id: "build", label: "Build your answer", shortLabel: "Build" },
    { id: "write", label: "Write the essay", shortLabel: "Write" },
    { id: "check", label: "Check & improve", shortLabel: "Check" },
    { id: "transfer", label: "Transfer and independent practice", shortLabel: "Transfer" },
  ],
  units: [
    { id: "u1", section: "understand", label: "Meet the question patterns", eyebrow: "Examples → notice" },
    { id: "u2", section: "understand", label: "The topic and the job", eyebrow: "Read → distinguish" },
    { id: "u3", section: "understand", label: "Judge the introduction", eyebrow: "Question → answer setup" },
    { id: "u3p", section: "understand", label: "Paraphrase without changing meaning", eyebrow: "Notice → judge → try → revise" },
    { id: "u4", section: "understand", label: "Is a position required?", eyebrow: "Similar topic → different job" },
    { id: "u5", section: "understand", label: "Write an introduction", eyebrow: "Understand → write → revise" },
    { id: "u6", section: "understand", label: "Keep the principle", eyebrow: "Collect what matters" },
    { id: "b1", section: "build", label: "Does this idea help?", eyebrow: "Topic → relevance" },
    { id: "b2", section: "build", label: "What does the idea need?", eyebrow: "Idea → explanation" },
    { id: "b3", section: "build", label: "Build the reasoning", eyebrow: "Why → meaning → support" },
    { id: "b4", section: "build", label: "Judge development", eyebrow: "Appearance → reasoning" },
    { id: "b5", section: "build", label: "Write a body paragraph", eyebrow: "Focus → develop → close" },
    { id: "b6", section: "build", label: "Collect the learning", eyebrow: "Experience → AES" },
    { id: "w1", section: "write", label: "What jobs must the essay do?", eyebrow: "Instruction → essay jobs" },
    { id: "w2", section: "write", label: "Which plan works?", eyebrow: "Jobs → paragraphs" },
    { id: "w3", section: "write", label: "Do the paragraphs work together?", eyebrow: "Progression → position" },
    { id: "w4", section: "write", label: "Do the beginning and ending fit?", eyebrow: "Beginning ↔ answer ↔ ending" },
    { id: "w5", section: "write", label: "Make a quick plan", eyebrow: "Fade support → plan quickly" },
    { id: "w6", section: "write", label: "Write the essay", eyebrow: "Plan → write → edit" },
    { id: "w7", section: "write", label: "Review the structure", eyebrow: "Intended → written" },
    { id: "c1", section: "check", label: "What needs attention?", eyebrow: "Diagnose with AES" },
    { id: "c2", section: "check", label: "What should be fixed first?", eyebrow: "Impact → priority" },
    { id: "c3", section: "check", label: "Revise your essay", eyebrow: "Feedback → choose → revise" },
    { id: "c4", section: "check", label: "Compare and reflect", eyebrow: "Before → after → effect" },
    { id: "c5", section: "transfer", label: "Try a new question", eyebrow: "New context → transfer" },
    { id: "c6", section: "transfer", label: "Keep the whole process", eyebrow: "Read → plan → build → write → check → revise" },
  ],
  patterns: [
    { id: "position", label: "Agreement or position", question: "Some people believe university education should be free for everyone. To what extent do you agree or disagree?", jobs: "Decide and support a position." },
    { id: "views", label: "Discuss views", question: "Some people think public parks should mainly provide quiet natural spaces, while others think they should provide sports facilities. Discuss both views and give your own opinion.", jobs: "Discuss both views and make your own position clear." },
    { id: "pros-cons", label: "Advantages and disadvantages", question: "In many workplaces, employees can work from home for part of the week. What are the advantages and disadvantages of this arrangement?", jobs: "Explain advantages and disadvantages; the question does not directly ask what you think." },
    { id: "outweigh", label: "Which side is stronger?", question: "More city centres are limiting private cars. Do the advantages of this policy outweigh the disadvantages?", jobs: "Consider both sides and judge which is greater." },
    { id: "problems", label: "Problems and solutions", question: "Home deliveries are increasing in many cities. What problems can this cause, and what solutions can you suggest?", jobs: "Explain relevant problems and propose connected solutions." },
    { id: "two-part", label: "Two related questions", question: "More adults are choosing to learn new skills online. Why is this happening? Is this a positive or negative development?", jobs: "Explain reasons and make the requested evaluation." },
  ],
  u2: {
    prompt: "Which statement identifies the job—not merely the topic?",
    shuffle: true,
    options: [
      { id: "job", text: "Explain the main advantages and disadvantages of employees working from home.", viable: true, feedback: "This identifies both jobs in the instruction: explain advantages and explain disadvantages." },
      { id: "topic", text: "Explain how working from home has become more common.", viable: false, feedback: "This is closely related to the subject, but the question does not ask why or how the arrangement became common." },
      { id: "partial", text: "Explain the advantages of working from home for employees.", viable: false, feedback: "This identifies one required job, but leaves out the disadvantages." },
      { id: "nearby", text: "Decide whether employers should allow their staff to work from home.", viable: false, feedback: "This creates a nearby opinion question. The actual instruction asks for advantages and disadvantages, not a decision about permission." },
    ],
    help: [
      "First find the broad subject. Then look at the words after it: what two things must the writer explain?",
      "‘Advantages and disadvantages’ creates two jobs. An answer that covers only one side is incomplete.",
    ],
  },
  u3: {
    question: "Some people think public parks should mainly provide quiet natural spaces, while others think they should provide sports facilities. Discuss both views and give your own opinion.",
    items: [
      { id: "complete", text: "Public parks can provide either peaceful natural areas or facilities for exercise. Both priorities have value, but I believe a successful park can support activity without losing its quiet character.", answer: "yes", feedback: "It establishes both views and makes the writer's position clear." },
      { id: "partial", text: "Public parks are important places where residents can relax, exercise and spend time outdoors.", answer: "partly", feedback: "It is relevant and grammatical, but it does not yet set up the two views or the writer's required opinion." },
      { id: "mismatch", text: "This essay will explain why every city should spend more money building new parks.", answer: "no", feedback: "It creates a different question about spending and park construction." },
    ],
    help: [
      "Check the exact instruction: the writer must discuss both views and make their own opinion clear.",
      "Ask three questions for each introduction: Can I see the first view? Can I see the other view? Can I see what the writer thinks?",
    ],
  },
  u3p: {
    question: "Some people believe that university education should be free for everyone. To what extent do you agree or disagree?",
    subjectView: "University education should be free for everyone.",
    job: "Decide and communicate how far you agree.",
    prompt: "Which statement keeps the main view and could fit naturally into an introduction?",
    shuffle: true,
    options: [
      { id: "clear-preserved", text: "Some people believe that everyone should be able to study at university without paying tuition fees.", viable: true, feedback: "The main meaning is preserved, the English is natural, and this statement could fit into an introduction. It does not try to replace every word." },
      { id: "narrow-group", text: "Some people believe that students from families with limited incomes should be able to attend university without paying tuition fees.", viable: false, feedback: "This is natural and could fit into an introduction, but it changes ‘everyone’ to one group of students. An important part of the meaning is narrower." },
      { id: "accurate-awkward", text: "It is a belief of some people that every person should be able to receive university education without paying fees.", viable: false, feedback: "The main meaning is mostly preserved, but the wording is indirect and less natural than it needs to be. Changing to an awkward passive-style structure is not a goal of paraphrasing." },
      { id: "reduced-fees", text: "Some people believe that university fees should be lower for all students.", viable: false, feedback: "This is natural and could fit into an introduction, but lower fees are not the same as no fees. Part of the original meaning is lost." },
    ],
    help: [
      "Write it as a statement that could belong in an essay, not as another question.",
      "Keep the same main meaning. You do not need to change every word.",
      "Check two details: university is free, and this applies to everyone. A possible beginning is ‘Some people believe that…’.",
    ],
    teachingExample: "Some people believe that everyone should be able to study at university without paying tuition fees.",
  },
  u4: {
    prompt: "Does the exact instruction require a personal position or judgement?",
    items: [
      { id: "describe", question: "What are the advantages and disadvantages of working from home?", answer: "no", feedback: "The writer must cover both sides, but the instruction does not directly ask for a personal judgement." },
      { id: "evaluate", question: "Do the advantages of working from home outweigh the disadvantages?", answer: "yes", feedback: "The writer must consider both sides and judge which side is stronger." },
      { id: "views", question: "Discuss both views and give your own opinion.", answer: "yes", feedback: "The instruction directly asks for the writer's opinion as well as both views." },
    ],
    help: [
      "Look for words that ask what the writer thinks, such as ‘give your own opinion’, ‘do you agree’ or ‘outweigh’.",
      "Describing advantages and disadvantages covers two sides. It becomes a judgement task only when the instruction also asks which side is stronger or what you think.",
    ],
  },
  u5: {
    question: "Some people believe that university education should be free for everyone. To what extent do you agree or disagree?",
    help: [
      "What does ‘to what extent’ require you to make clear about your opinion?",
      "Establish the tuition question and show how strongly you agree or disagree. You do not need an attention-grabbing opening or a long background.",
      "University fees can prevent some capable students from continuing their education. Although I agree that financial barriers should be reduced, I believe targeted support is more practical than making every course free for every student.",
    ],
    aiFeedback: {
      stage: "Task 2 introduction",
      taught: ["Let the exact question decide what the introduction needs to do.", "Establish the subject and set up the answer.", "Make a position identifiable only when the instruction requires one.", "Accept simple dependable language when it performs the job."],
      criteria: ["fit with the exact instruction", "clarity and degree of the writer's position", "relevance", "natural and grammatically clear language"],
      exclusions: ["Do not evaluate missing body development or a conclusion.", "Do not require a hook, background history, an outline sentence or a fixed number of sentences.", "Do not criticise 'This essay will...' merely because it is formulaic if it performs the required job."],
    },
  },
  b1: {
    labels: [
      { id: "helps", text: "Helps answer it" },
      { id: "could", text: "Could help — make the connection" },
      { id: "topic", text: "Only about the topic" },
    ],
    shuffle: true,
    ideas: [
      { id: "access", text: "Free tuition may widen access for capable students whose families cannot afford fees.", answer: "helps", feedback: "This directly supports agreement by connecting cost with access." },
      { id: "priorities", text: "Funding tuition for everyone may leave less money for other public services.", answer: "helps", feedback: "This directly supports disagreement or a position that agrees only partly." },
      { id: "quality", text: "Universities need stable funding to maintain teaching quality.", answer: "could", feedback: "This could matter if the writer connects funding sources to whether tuition should be free." },
      { id: "formats", text: "University courses commonly include lectures, seminars and independent study.", answer: "topic", feedback: "This is about university, but it does not address whether tuition should be free." },
      { id: "course-choice", text: "University students often choose courses according to their future career goals.", answer: "topic", feedback: "This is a genuine point about students and education, but it does not yet help the writer judge whether university should be free for everyone." },
    ],
    help: [
      "Complete this sentence: ‘This idea helps me agree or disagree because…’ If you cannot complete it, the connection may be missing.",
      "An idea can be true and connected to university without answering the tuition question. Look for a clear link to cost, access, fairness or public funding.",
    ],
  },
  b2: {
    idea: "Free university education could improve access for students from lower-income families.",
    prompt: "Which sentences genuinely move this idea forward? Select every continuation that develops it well.",
    shuffle: true,
    options: [
      { id: "barrier", text: "High fees may prevent capable students from applying or attending, even when they meet the academic requirements.", viable: true, feedback: "This explains how cost can restrict access." },
      { id: "income", text: "Removing tuition costs could therefore make family income less important in deciding who can enter higher education.", viable: true, feedback: "This develops a plausible result of removing the barrier." },
      { id: "debt", text: "It could also make attendance more practical for students who would otherwise avoid large debts.", viable: true, feedback: "This is another useful way to develop the idea." },
      { id: "repeat", text: "Therefore, free university would improve access for lower-income students.", viable: false, feedback: "This mainly repeats the idea without showing why or how." },
      { id: "outcome", text: "Students who attend university may improve their employment opportunities after graduation.", viable: false, feedback: "This could support a different argument about the benefits of university, but it does not explain how free tuition improves access for lower-income students." },
    ],
    help: [
      "After the main idea, ask: ‘Why could this happen?’ or ‘What would change because of it?’",
      "A useful next sentence should explain the connection between tuition cost and access. Repeating ‘access improves’ is not enough.",
    ],
  },
  b3: {
    positions: ["I agree", "I mostly agree", "I mostly disagree", "I disagree", "I want to write my position differently"],
    ideas: [
      { id: "access", text: "Free tuition can widen access for students with limited family income." },
      { id: "public-money", text: "Universal free tuition can place a large demand on public money." },
      { id: "targeted", text: "Targeted financial help may be fairer than paying tuition for every student." },
    ],
    whys: [
      { id: "fees-barrier", idea: "access", text: "High fees can prevent capable students from attending." },
      { id: "debt-risk", idea: "access", text: "Some students may avoid higher education because they fear long-term debt." },
      { id: "other-services", idea: "public-money", text: "Governments also need to fund schools, health services, roads and other public systems." },
      { id: "wealthy-benefit", idea: "targeted", text: "Universal funding would also pay for students whose families can afford the fees." },
    ],
    supports: [
      { id: "income-access", idea: "access", text: "As a result, family income may have less influence on access to higher education." },
      { id: "hypothetical", idea: "access", text: "For example, a capable student from a low-income family may decide not to apply when the fees are unaffordable." },
      { id: "tradeoff", idea: "public-money", text: "This could leave less funding for public services that benefit a wider population." },
      { id: "target-help", idea: "targeted", text: "Directing support towards students who need it could widen access while limiting the public cost." },
      { id: "enough", idea: "all", text: "My reason is clear enough for this planning note; I do not need another step." },
    ],
  },
  b4: {
    prompt: "How well does each version develop the access idea?",
    shuffle: true,
    options: [
      { id: "reasoning", text: "Free tuition could widen access because high fees may prevent capable students from attending. Removing this cost would mean family income has less influence on who can continue into higher education.", answer: "strong", feedback: "This develops the idea with a clear reason and consequence." },
      { id: "repeat", text: "Free tuition improves access. When tuition is free, access becomes better, so more students have improved access to university.", answer: "weak", feedback: "The sentences remain relevant, but they mostly repeat ‘access improves’ without explaining why." },
      { id: "authority", text: "A 2025 study from a well-known university found that 87% of students succeed when tuition is free. This proves that free university education improves access.", answer: "weak", feedback: "The source and statistic have been invented to make the claim sound convincing. They also discuss success rather than explaining how tuition affects access." },
      { id: "alternative", text: "Free tuition may reduce students’ fear of debt, so they may feel able to consider university and a wider choice of courses.", answer: "could", feedback: "This could develop the idea through debt and educational choice, but it should connect more clearly to access for students who cannot afford fees." },
    ],
    help: [
      "Ask what new understanding each version gives after the main claim. Does it explain why, how or what happens next?",
      "Relevant words and extra sentences are not enough. Look for a clear reasoning link, and be cautious when a writer presents a precise study they do not genuinely know.",
    ],
  },
  b5: {
    help: [
      "What useful contribution will this paragraph make to your answer?",
      "Explain why or how the idea works. Add only the result, clearer detail, comparison or realistic situation the reader needs.",
      "Free tuition could widen access because high fees may prevent capable students from attending even when they meet the academic requirements. For example, a student from a family with limited income may decide not to apply if the cost would create debt they cannot manage. Removing this barrier would make family income less important in determining who can continue into higher education.",
    ],
    aiFeedback: {
      stage: "one Task 2 body paragraph",
      taught: ["The paragraph should make a useful contribution to the answer.", "Explain and support the main idea sufficiently.", "Support may be reasoning, consequence, comparison, clarification, a realistic situation or example.", "Close when the idea's argumentative work is complete."],
      criteria: ["contribution to answering the question", "clarity of the main idea", "explanation", "sufficient relevant support", "irrelevance or repetition", "understandable reasoning", "clear language"],
      exclusions: ["Do not score the whole essay.", "Do not demand an introduction, conclusion or other body paragraph.", "Do not require a statistic, an example, difficult vocabulary or a special linking sentence."],
    },
  },
  w1: {
    tasks: [
      { id: "views", instruction: "Discuss both views and give your own opinion.", required: ["view-a", "view-b", "position"], jobs: [{ id: "view-a", text: "Discuss the first view" }, { id: "view-b", text: "Discuss the other view" }, { id: "position", text: "Make the writer's own view clear" }, { id: "causes", text: "Explain what caused the disagreement" }] },
      { id: "problem", instruction: "What problems does this cause and what solutions can you suggest?", required: ["problems", "solutions"], jobs: [{ id: "problems", text: "Explain relevant problems" }, { id: "solutions", text: "Propose connected solutions" }, { id: "position", text: "Decide whether the situation is positive or negative" }, { id: "causes", text: "Explain why the situation has become more common" }] },
      { id: "outweigh", instruction: "Do the advantages outweigh the disadvantages?", required: ["advantages", "disadvantages", "judgement"], jobs: [{ id: "advantages", text: "Consider advantages" }, { id: "disadvantages", text: "Consider disadvantages" }, { id: "judgement", text: "Judge which side is stronger" }, { id: "solutions", text: "Suggest how the disadvantages could be solved" }] },
    ],
    help: [
      "Turn each instruction into a short list of jobs. Select only work the exact words require.",
      "A nearby Task 2 question might ask for causes, solutions or an evaluation. That does not make those jobs necessary here.",
    ],
  },
  w2: {
    shuffle: true,
    options: [
      { id: "reliable", label: "Plan A", text: "Introduction: mostly agree. Body 1: explain how fees restrict access. Body 2: explain why help for students who need it may be more practical than paying for everyone. Conclusion: restate the partly-agree position.", status: "works", feedback: "This gives two clearly different contributions enough room to develop and keeps the partly-agree position." },
      { id: "alternative", label: "Plan B", text: "Introduction: disagree with universal free tuition. Body 1: explain pressure on public budgets. Body 2: explain targeted grants as a fairer way to widen access. Body 3: briefly address the opposing access argument. Conclusion: close the judgement.", status: "could", feedback: "This can work if the writer can develop three distinct contributions within the available time. It is not wrong because it has five paragraphs." },
      { id: "thin", label: "Plan C", text: "Introduction. Body 1: access, debt, graduate employment, university buildings and social life. Body 2: taxes, hospitals, school funding, fairness and research. Conclusion.", status: "weak", feedback: "The ideas are relevant in places, but spreading attention across so many points risks mention without development." },
      { id: "overlap", label: "Plan D", text: "Introduction: mostly agree. Body 1: poorer students cannot afford fees. Body 2: students with little money face financial barriers and may not attend. Conclusion: government should help students.", status: "could", feedback: "The plan is relevant, but the two body paragraphs repeat much of the same contribution. It could work if the writer combines them and adds another necessary part of the partly-agree answer." },
    ],
  },
  w3: {
    progression: [
      { id: "coherent", text: "Body 1 explains how fees restrict access. Body 2 limits the argument by considering public cost and support for students who need it most.", viable: true, feedback: "The paragraphs make different connected contributions to one partly-agree answer." },
      { id: "repeat", text: "Body 1 explains that fees restrict poorer students. Body 2 explains again that students without money cannot pay fees.", viable: false, feedback: "Different wording does not move the answer forward when the contribution is essentially repeated." },
      { id: "underdeveloped", text: "Body 1 explains how fees restrict access. Body 2 lists the costs of staff, libraries and technology but does not connect these costs to who should pay tuition.", viable: false, feedback: "Both paragraphs contain relevant material, but the second does not explain how university costs affect the answer to the question." },
    ],
    consistency: [
      { id: "qualify", text: "Recognise the public-cost concern, then explain why it supports targeted help rather than abandoning the overall access position.", viable: true, feedback: "This allows the other concern to matter while keeping the writer's overall position clear." },
      { id: "opposite", text: "Use the second paragraph to argue that free tuition is always unfair, without explaining how this fits the earlier mostly-agree position.", viable: false, feedback: "This creates a different position rather than developing or carefully limiting the position already stated." },
      { id: "unclear-balance", text: "Present access and public cost as equally important, then leave the reader to decide what the writer believes.", viable: false, feedback: "Both ideas can be relevant, but this does not keep the required personal position clear." },
    ],
    help: [
      "Give each paragraph a short job. Do the jobs move the same answer forward, or do they repeat or pull in different directions?",
      "Imagine removing words such as ‘however’ or ‘on the other hand’. Can you still see how the second paragraph develops or limits the first?",
    ],
  },
  w4: {
    bodyPlan: "The essay mostly agrees that costs should not block capable students, but argues that financial help for students who need it is more practical than paying the fees of every student.",
    conclusions: [
      { id: "close", text: "In conclusion, tuition costs should not prevent capable students from entering university, but targeted financial support is a more practical policy than making every course free for everyone.", viable: true, feedback: "This clearly closes the partly-agree answer developed in the essay." },
      { id: "incomplete", text: "In conclusion, university fees can create serious barriers for capable students.", viable: false, feedback: "This is relevant and clear, but it closes only the access idea and leaves out the writer's judgement about targeted rather than universal support." },
      { id: "reader", text: "In conclusion, you should help students who cannot pay, but you should not make university free for everybody.", viable: false, feedback: "The main judgement fits, but direct advice to ‘you’ sounds more like a conversation with the reader than an essay conclusion. It could work after a style change." },
      { id: "formal", text: "In conclusion, the allocation of targeted financial assistance represents a preferable policy to the universal removal of tuition charges.", viable: false, feedback: "The judgement broadly fits, but the wording is more formal and indirect than necessary. Clearer natural English would communicate it more efficiently." },
      { id: "stronger", text: "In conclusion, university education should be completely free for every student, despite the pressure this may place on public funding.", viable: false, feedback: "This changes the writer's partly-agree position into complete agreement." },
    ],
    help: [
      "Compare each conclusion with the answer the body developed. Does it include both access and the preference for targeted support?",
      "A conclusion can be relevant but incomplete, change the strength of the position, speak directly to the reader or use more formal language than needed.",
    ],
  },
  c1: {
    paragraphs: [
      { id: "intro", label: "Introduction", text: "University tuition can create a serious barrier for some students. Although I agree that governments should widen access, I do not believe every student should automatically receive free tuition.", issue: false },
      { id: "access", label: "Body paragraph 1", text: "The strongest reason for public support is that high fees can prevent capable students from attending. A student from a low-income family may meet every academic requirement but decide not to apply because the cost would create unmanageable debt. Targeted funding can reduce this barrier and make access depend less on family income.", issue: false },
      { id: "funding", label: "Body paragraph 2", text: "On the other hand, universities need stable funding because education is important. Furthermore, governments spend money on many services, and university courses can be expensive to provide. This is a significant issue for modern society.", issue: true },
      { id: "conclusion", label: "Conclusion", text: "In conclusion, university should be completely free for every student because this is the fairest approach.", issue: true },
    ],
  },
  c2: {
    shuffle: true,
    options: [
      { id: "position", text: "Make the conclusion match the partly-agree position stated and developed in the essay.", priority: 1, feedback: "This affects the answer as a whole: the reader currently receives two different positions." },
      { id: "develop", text: "Explain how the funding concern affects the choice between free tuition for everyone and support for students who need it.", priority: 2, feedback: "This is the next important issue because the second main contribution is stated but not developed." },
      { id: "word", text: "Replace the clear word ‘important’ with ‘significant’.", priority: 4, feedback: "This changes appearance more than meaning and should not take priority over the answer and reasoning." },
      { id: "punctuation", text: "Correct one minor punctuation slip.", priority: 3, feedback: "Accuracy matters, but this local issue has less effect than the inconsistent answer and underdeveloped main idea." },
      { id: "connector", text: "Use ‘However’ to make the move from access to the funding concern clearer.", priority: 3, feedback: "This could help the reader notice the contrast later, but it cannot replace the missing explanation of why funding affects the tuition judgement." },
    ],
    help: [
      "Ask which change would most affect the reader's understanding of the writer's answer as a whole.",
      "Some smaller changes may still help later. First compare the inconsistent conclusion with the underdeveloped funding idea, then consider local wording and linking.",
    ],
  },
  teachingExample: {
    paragraphs: [
      "University fees can prevent some capable students from continuing their education. Although I agree that financial barriers should be reduced, I believe targeted public support is more practical than making every university course free for every student.",
      "Students from lower-income families may decide not to apply when tuition would create debt they cannot manage. This means academic ability is not the only factor determining access. Grants or reduced fees for these students can therefore make higher education more accessible without requiring them to take an unreasonable financial risk.",
      "However, universities also need reliable funding for teaching, facilities and student services. If governments paid every student's fees, including those whose families can afford them, less public money might remain for schools, healthcare or targeted university grants. Concentrating support on students who face a genuine financial barrier could protect access while using public funds more carefully.",
      "In conclusion, cost should not prevent capable students from attending university, but targeted support offers a fairer and more sustainable solution than universal free tuition.",
    ],
    lenses: [
      { id: "task", label: "Task Response", note: "The writer partly agrees, develops access and public-cost reasoning, and keeps the same position throughout." },
      { id: "coherence", label: "Coherence and Cohesion", note: "Each paragraph makes a distinct contribution, and the contrast follows from the reasoning rather than from connectors alone." },
      { id: "lexical", label: "Lexical Resource", note: "Words such as ‘financial barrier’, ‘targeted support’ and ‘public funds’ are precise and natural without being decorative." },
      { id: "grammar", label: "Grammatical Range and Accuracy", note: "Sentence forms vary where useful, while relationships remain clear and controlled." },
    ],
  },
  ai: {
    fullEssay: {
      stage: "complete Task 2 essay",
      taught: ["Answer the exact instruction and complete every required job.", "Maintain a clear and consistent position when required.", "Use paragraphs with useful contributions and clear progression.", "Explain and support relevant main ideas.", "Use clear, natural and controllable language."],
      criteria: ["Task Response: task coverage, position, relevance and development", "Coherence and Cohesion: organisation, paragraph contribution, progression, repetition and useful linking", "Lexical Resource: clear, appropriate, natural and sufficiently varied word choice", "Grammatical Range and Accuracy: clear meaning, controlled variety and recurring problems that affect communication"],
      exclusions: ["Do not give a band score or claim to be an official IELTS examiner.", "Do not immediately rewrite the essay.", "Do not demand advanced vocabulary, a statistic, an example, four paragraphs or exactly two main ideas.", "Do not correct every sentence indiscriminately.", "Do not treat reaching 250 words as proof of quality; below 250, identify the requirement calmly and diagnose what may need development."],
    },
    revision: {
      stage: "revision of a complete Task 2 essay",
      taught: ["Revision should improve a chosen problem in the learner's existing response.", "Judge whether the current revision makes the intended meaning, reasoning, organisation or language clearer.", "Prioritise the learner's selected revision goal before starting any broader critique."],
      criteria: ["whether the chosen revision priority improved", "whether the change preserved useful parts of the original", "the most important remaining issue connected to that priority", "a concrete next revision the learner can make"],
      exclusions: ["Do not restart a complete first-pass essay review unless a serious problem makes that necessary.", "Do not give a band score or claim to be an official IELTS examiner.", "Do not rewrite the essay or provide a corrected version immediately.", "Do not demand advanced vocabulary, extra features or changes unrelated to the selected priority."],
    },
    transfer: {
      stage: "independent Task 2 transfer essay",
      taught: ["The instruction asks for advantages and disadvantages, not a personal opinion or an outweigh judgement.", "Answer both required jobs.", "Develop relevant contributions with explanation and support.", "Organise the answer clearly and close it without starting a new argument."],
      criteria: ["Task Response: coverage of both advantages and disadvantages without forcing an unrequested judgement", "Coherence and Cohesion: useful paragraph contributions and progression", "Lexical Resource: clear and appropriate wording", "Grammatical Range and Accuracy: clear meaning and useful priorities"],
      exclusions: ["Do not give a band score or claim to be an official IELTS examiner.", "Do not require a personal opinion, an outweigh judgement, a fixed paragraph count, difficult vocabulary or invented evidence.", "Do not immediately rewrite or correct every sentence.", "Do not treat 250 words as a quality score or block diagnosis below it."],
    },
  },
};
