export const task2Content = {
  id: "writing-task-2-v0-1",
  title: "IELTS Writing Task 2",
  canonicalQuestion: "Some people believe that university education should be free for everyone. To what extent do you agree or disagree?",
  transferQuestion: "In many workplaces, employees can now work from home for some or all of the week. What are the advantages and disadvantages of this arrangement?",
  orderPolicy: {
    principle: "Randomise choices unless order is part of the meaning.",
    semanticOrderExceptions: {
      "workshop-units": "The learning sequence is cumulative.",
      "u3-judgement-scale": "Yes → Partly → No is an ordered scale.",
      "u6-learning-sequence": "Topic → job → introduction is a teaching sequence.",
      "b1-classification-scale": "The categories move from direct contribution to topic-only relevance.",
      "b3-position-scale": "Agreement choices form an ordered continuum.",
      "b4-development-scale": "Strong → could work → weak is an ordered scale.",
      "b6-aes-sequence": "Answer → Explain → Support is the taught checking sequence.",
      "w2-plan-scale": "The plan judgements form an ordered quality scale.",
      "w5-plan-fields": "The plan follows task → position → body contributions.",
      "w7-review-sequence": "The prompts and Yes → Partly → Not yet scale support an ordered structural review.",
      "c1-paragraph-sequence": "The paragraphs must remain in essay order.",
      "c4-before-after": "Original must precede revised writing for comparison.",
      "c4-criteria-sequence": "The teaching lenses retain the official criteria sequence.",
      "c6-process-sequence": "Read → plan → build → write → check → revise is the process being learned.",
    },
  },
  sections: [
    { id: "understand", label: "Understand the question", shortLabel: "Understand" },
    { id: "plan", label: "From question to plan", shortLabel: "Plan" },
    { id: "introduce", label: "Look at introductions", shortLabel: "Introductions" },
    { id: "write", label: "Write an introduction", shortLabel: "Write" },
    { id: "finish", label: "Finish Workshop 1", shortLabel: "Finish" },
  ],
  units: [
    { id: "u1", section: "understand", label: "What do I have to do?", eyebrow: "Question 1 · Problems and solutions" },
    { id: "u2", section: "understand", label: "Say what you think", eyebrow: "Question 2 · Agree or disagree" },
    { id: "q3", section: "understand", label: "Discuss two views", eyebrow: "Question 3 · Two views and your opinion" },
    { id: "q4", section: "understand", label: "Find the two sides", eyebrow: "Question 4 · Advantages and disadvantages" },
    { id: "q5", section: "understand", label: "Answer both questions", eyebrow: "Question 5 · Two questions" },
    { id: "n1", section: "understand", label: "Answer the task you are given", eyebrow: "Now name the learning" },
    { id: "s1", section: "plan", label: "Four clear parts", eyebrow: "What are we going to write?" },
    { id: "p1", section: "plan", label: "Read Shaima's plan", eyebrow: "A student makes a plan" },
    { id: "p2", section: "plan", label: "Choose what to see next", eyebrow: "Optional plan exploration" },
    { id: "i1", section: "introduce", label: "Look at their introductions", eyebrow: "From plan to writing" },
    { id: "i2", section: "introduce", label: "Why didn't Mustafa say ‘I agree’?", eyebrow: "Return to the question" },
    { id: "f1", section: "introduce", label: "Can you help Fatma?", eyebrow: "Help someone write" },
    { id: "f2", section: "introduce", label: "Compare yours with Fatma's", eyebrow: "One possible introduction" },
    { id: "o1", section: "write", label: "What do I have to talk about?", eyebrow: "Now try it yourself" },
    { id: "o2", section: "write", label: "Make a small plan", eyebrow: "Three useful notes" },
    { id: "o3", section: "write", label: "Write your introduction", eyebrow: "Your turn" },
    { id: "end", section: "finish", label: "Workshop 1 complete", eyebrow: "Question to introduction" },
  ],
  laterTask2Units: [
    { id: "b1", section: "build", label: "Does this idea help?", eyebrow: "Start with the question" },
    { id: "b2", section: "build", label: "What does the next sentence do?", eyebrow: "Look at the next sentence" },
    { id: "b3", section: "build", label: "Build your idea", eyebrow: "Move the idea forward" },
    { id: "b4", section: "build", label: "Which paragraph explains the idea?", eyebrow: "More words are not always better" },
    { id: "b5", section: "build", label: "Write a body paragraph", eyebrow: "Now write" },
    { id: "b6", section: "build", label: "A simple paragraph check", eyebrow: "Keep three useful questions" },
    { id: "w1", section: "write", label: "What must the essay do?", eyebrow: "Read the question again" },
    { id: "w2", section: "write", label: "Which plan works?", eyebrow: "Choose a clear plan" },
    { id: "w3", section: "write", label: "Do the paragraphs work together?", eyebrow: "Put ideas in a clear order" },
    { id: "w4", section: "write", label: "Do the beginning and ending fit?", eyebrow: "Check the beginning and ending" },
    { id: "w5", section: "write", label: "Make a quick plan", eyebrow: "Plan before writing" },
    { id: "w6", section: "write", label: "Write the essay", eyebrow: "Now write" },
    { id: "w7", section: "write", label: "Check your plan and essay", eyebrow: "Did the plan help?" },
    { id: "c1", section: "check", label: "What needs attention?", eyebrow: "Find what needs work" },
    { id: "c2", section: "check", label: "What should be fixed first?", eyebrow: "Fix the biggest problem first" },
    { id: "c3", section: "check", label: "Improve your essay", eyebrow: "Make one useful change" },
    { id: "c4", section: "check", label: "Compare before and after", eyebrow: "What changed?" },
    { id: "c5", section: "transfer", label: "Try a new question", eyebrow: "Use the same steps again" },
    { id: "c6", section: "transfer", label: "Keep the whole process", eyebrow: "Use the full process" },
  ],
  patterns: [
    { id: "position", label: "Agreement or position", question: "Some people believe university education should be free for everyone. To what extent do you agree or disagree?", jobs: "Decide and support a position." },
    { id: "views", label: "Discuss views", question: "Some people think public parks should mainly provide quiet natural spaces, while others think they should provide sports facilities. Discuss both views and give your own opinion.", jobs: "Discuss both views and make your own position clear." },
    { id: "pros-cons", label: "Advantages and disadvantages", question: "In many workplaces, employees can work from home for part of the week. What are the advantages and disadvantages of this arrangement?", jobs: "Explain advantages and disadvantages; the question does not directly ask what you think." },
    { id: "outweigh", label: "Which side is stronger?", question: "More city centres are limiting private cars. Do the advantages of this policy outweigh the disadvantages?", jobs: "Consider both sides and judge which is greater." },
    { id: "problems", label: "Problems and solutions", question: "Home deliveries are increasing in many cities. What problems can this cause, and what solutions can you suggest?", jobs: "Explain relevant problems and propose connected solutions." },
    { id: "two-part", label: "Two related questions", question: "More adults are choosing to learn new skills online. Why is this happening? Is this a positive or negative development?", jobs: "Explain reasons and make the requested evaluation." },
  ],
  opening: {
    introduction: "In Task 2, you will be given a question. Task 2 questions can ask you to do different things. Here are five common kinds of question we will practise. The wording can change, so always read the question carefully.",
    problems: {
      statement: "In many countries, increasing numbers of adults and children are becoming obese.",
      instruction: "What are the main <strong>causes</strong> of this problem, and what <strong>solutions</strong> can you suggest?",
      jobs: [
        { id: "why", text: "I have to talk about why the problem happens." },
        { id: "solve", text: "I have to talk about ways to solve the problem." },
        { id: "opinion", text: "I have to say if I agree or disagree." },
        { id: "views", text: "I have to talk about two different opinions." },
      ],
      matches: { causes: "why", solutions: "solve" },
      lexical: [
        { word: "obese", meaning: "very overweight", arabic: "بدين / مصاب بالسمنة" },
        { word: "cause", meaning: "why something happens", arabic: "سبب" },
        { word: "solution", meaning: "a way to solve a problem", arabic: "حل" },
      ],
    },
    agree: {
      statement: "Some people believe that university education should be free for everyone.",
      instruction: "To what extent do you <strong>agree or disagree</strong>?",
      jobs: [
        { id: "degree", text: "I have to say how much I agree or disagree." },
        { id: "two-views", text: "I have to explain two different opinions." },
        { id: "solutions", text: "I have to suggest solutions." },
      ],
      consistency: [
        { id: "unclear", text: "My answer is not clear. This could affect my score." },
        { id: "stronger", text: "My answer becomes stronger because I changed my mind." },
        { id: "no-effect", text: "Nothing changes because both ideas are about university." },
      ],
      lexical: [
        { word: "tuition fees", meaning: "money paid for university teaching", arabic: "الرسوم الدراسية" },
        { word: "agree", meaning: "have the same opinion", arabic: "يوافق" },
        { word: "disagree", meaning: "have a different opinion", arabic: "لا يوافق / يعارض" },
      ],
    },
    views: {
      statement: "Some people think public parks should mainly provide quiet natural spaces. Others think they should provide sports facilities.",
      instruction: "<strong>Discuss both views</strong> and <strong>give your own opinion</strong>.",
      example: "I explain why quiet natural spaces are useful. I also explain why sports facilities are useful. Then I clearly say what I think.",
      outcomes: [
        { id: "all", text: "I did all the jobs in the question." },
        { id: "one", text: "I only explained one view." },
        { id: "different", text: "I answered a different question about park costs." },
      ],
      lexical: [
        { word: "view", meaning: "an opinion or way of thinking", arabic: "وجهة نظر" },
        { word: "discuss", meaning: "explain and consider an idea", arabic: "يناقش" },
        { word: "facilities", meaning: "places or equipment people can use", arabic: "مرافق" },
      ],
    },
    advantages: {
      statement: "In many workplaces, employees can now work from home for some or all of the week.",
      instruction: "What are the <strong>advantages and disadvantages</strong> of this arrangement?",
      jobs: [
        { id: "sides", text: "I have to talk about the good and bad sides." },
        { id: "opinion", text: "I have to say if everyone should work from home." },
        { id: "causes", text: "I have to explain why working from home began." },
      ],
      lexical: [
        { word: "advantage", meaning: "a good or helpful side", arabic: "ميزة / جانب إيجابي" },
        { word: "disadvantage", meaning: "a bad or difficult side", arabic: "عيب / جانب سلبي" },
        { word: "arrangement", meaning: "the way something is organised", arabic: "نظام العمل" },
      ],
    },
    twoQuestions: {
      statement: "In many countries, people are choosing to have children later in life.",
      instruction: "<strong>Why is this happening?</strong><br/><strong>Is this a positive or negative development?</strong>",
      jobs: [
        { id: "why", text: "Explain why people are having children later." },
        { id: "judge", text: "Say whether this change is positive or negative." },
        { id: "solutions", text: "Suggest ways to make people have children earlier." },
        { id: "views", text: "Discuss two different opinions about families." },
      ],
      required: ["why", "judge"],
      lexical: [
        { word: "positive", meaning: "good or helpful", arabic: "إيجابي" },
        { word: "negative", meaning: "bad or harmful", arabic: "سلبي" },
        { word: "development", meaning: "a change or new situation", arabic: "تطور / تغير" },
      ],
    },
  },
  workshop1: {
    shaima: {
      question: "Some people believe that university education should be free for everyone. To what extent do you agree or disagree?",
      plan: [
        { title: "Introduction", lines: ["My answer: I agree.", "Say what my essay will explain."] },
        { title: "Main paragraph 1 — Opportunity", lines: ["Main idea: Fees can stop students from lower-income families going to university.", "Example: A farming family I know in Taqah. Their son studied engineering at UTAS. He later got a job with a renewable-energy company."] },
        { title: "Main paragraph 2 — Financial pressure", lines: ["Main idea: University costs can create long-term financial problems.", "Debt may take years to repay.", "Starting salaries may be low.", "This can be especially difficult for lower-income families."] },
        { title: "Conclusion", lines: ["Return to my answer.", "Bring my two main reasons together."] },
      ],
      reactions: [
        { id: "person", text: "It makes the argument easier to understand because we can see how it affects a real person.", feedback: "Yes, a specific person can help the reader see how the main idea works in a real situation." },
        { id: "limit", text: "It is useful, but one family's experience does not tell us what usually happens.", feedback: "That is a careful judgement. The example illustrates Shaima's idea, but it is not evidence of a general trend." },
        { id: "concrete", text: "It makes an abstract idea more concrete.", feedback: "Yes. The example turns the general idea of opportunity into a situation the reader can picture." },
        { id: "different", text: "I would probably choose a different example.", feedback: "That is reasonable. Writers can support the same main idea with different relevant examples." },
      ],
    },
    yusuf: {
      question: "Some people think public parks should mainly provide quiet natural spaces, while others think they should include more sports facilities. Discuss both views and give your own opinion.",
      plan: [
        { title: "Introduction", lines: ["There are two views.", "My position: develop more sports facilities."] },
        { title: "Main paragraph 1 — Access", lines: ["Gym membership can be expensive.", "Public facilities give more people somewhere to exercise.", "Cost should not prevent people from being active."] },
        { title: "Main paragraph 2 — Different needs", lines: ["Consider children, older people, casual users and people who exercise regularly.", "Different areas and equipment can meet different needs."] },
        { title: "Conclusion", lines: ["Parks should remain pleasant public spaces, but sports facilities should be an important part of their design."] },
      ],
      reactions: [
        { id: "clear", text: "His position is clear from the beginning.", feedback: "Yes. Yusuf tells the reader which view he supports before presenting his reasons." },
        { id: "access", text: "The first paragraph connects cost with access to exercise.", feedback: "Yes. The plan shows why public facilities could matter to people who cannot afford a gym." },
        { id: "balance", text: "I want him to explain the quiet-space view carefully too.", feedback: "That is a useful observation. The question asks him to discuss both views, even though he supports sports facilities." },
      ],
    },
    mustafa: {
      question: "In many countries, increasing numbers of adults and children are becoming obese. What are the main causes of this problem, and what solutions can you suggest?",
      plan: [
        { title: "Introduction", lines: ["Identify important causes: changes in diet and lower physical activity.", "Say the essay will consider practical solutions."] },
        { title: "Main paragraph 1 — Causes", lines: ["Convenient food can contain many calories.", "Busy families may depend more on prepared food.", "People may drive short distances.", "Many jobs involve sitting for long periods."] },
        { title: "Main paragraph 2 — Solutions", lines: ["Healthier food choices in schools and workplaces.", "Safe places to walk and exercise.", "Make some short journeys easier on foot."] },
        { title: "Conclusion", lines: ["There is no single cause, so there is no single solution.", "Changes to food and everyday activity can work together."] },
      ],
      reactions: [
        { id: "connect", text: "His solutions connect clearly to the causes in his first paragraph.", feedback: "Yes. The food and activity solutions respond directly to the causes Mustafa identified." },
        { id: "practical", text: "The plan uses practical changes instead of one very large solution.", feedback: "Yes. Mustafa combines several realistic changes because he has identified more than one cause." },
        { id: "develop", text: "I would like more detail about how one solution would work.", feedback: "That is reasonable. A plan can stay brief, but Mustafa will need to explain his chosen solutions in the essay." },
      ],
    },
    introductions: {
      shaima: "Some people believe that university education should be free for everyone. I agree with this view, and in this essay I will explain why free university education can create opportunities and reduce financial pressure on students.",
      yusuf: "Some people believe that public parks should provide quiet natural spaces, while others think they should include more sports facilities. I support developing more sports facilities, and I will explain why they can make exercise accessible to more people.",
      mustafa: "Obesity is becoming more common in many countries. I believe that changes in diet and lower levels of physical activity are important causes of this problem, and this essay will consider practical ways of addressing both.",
    },
    fatma: {
      question: "Some people believe that schools should teach practical skills such as cooking and managing money. To what extent do you agree or disagree?",
      plan: ["My answer: I agree.", "Paragraph 1: practical skills help young people become more independent.", "Paragraph 2: money skills can help them make better decisions."],
      choices: [
        { id: "direct", text: "Some people believe that schools should teach practical skills such as cooking and managing money. I agree because these skills can help young people become more independent and make better financial decisions." },
        { id: "balanced", text: "Teaching practical skills at school could prepare young people for everyday life. I support this idea, particularly because independence and sensible decisions about money are important after leaving school." },
      ],
      words: ["practical skills", "schools should teach", "I agree", "independent", "better decisions"],
      model: "Some people believe that schools should teach practical skills such as cooking and managing money. I agree with this view because these skills can help young people become more independent and make better decisions in everyday life.",
    },
    own: {
      question: "More adults are choosing to study courses online instead of attending classes in person. Why is this happening? Is this a positive or negative development?",
      jobs: [
        { id: "reasons", text: "Explain why more adults are choosing online courses." },
        { id: "judge", text: "Say whether this is a positive or negative development." },
        { id: "compare", text: "Compare the quality of every online and classroom course." },
        { id: "solutions", text: "Suggest ways to close online courses." },
      ],
      required: ["reasons", "judge"],
      lexical: [
        { word: "in person", meaning: "in the same physical place, not online", arabic: "وجهاً لوجه" },
        { word: "development", meaning: "a change or new situation", arabic: "تطور / تغير" },
        { word: "positive", meaning: "good or helpful", arabic: "إيجابي" },
      ],
    },
    topicSentence: {
      notes: ["Different people have different exercise needs.", "Children need places to be active.", "Older people may need gentler exercise.", "Some adults want more demanding exercise."],
      choices: [
        { id: "main", text: "Public sports facilities should meet the different exercise needs of people in the community." },
        { id: "list", text: "Children, older people and adults all exercise in different ways at different times." },
      ],
      words: ["different people", "different needs", "public facilities", "exercise"],
      model: "Public sports facilities should meet the different exercise needs of people in the community.",
    },
  },
  b1: {
    labels: [
      { id: "helps", text: "Helps answer it" },
      { id: "could", text: "Could help — make the connection" },
      { id: "topic", text: "Only about the topic" },
    ],
    shuffle: true,
    ideas: [
      { id: "access", core: true, text: "Free tuition may widen access for capable students whose families cannot afford fees.", answer: "helps", feedback: "This gives a clear reason to agree: cost can stop some students from attending." },
      { id: "priorities", core: false, text: "Funding tuition for everyone may leave less money for other public services.", answer: "helps", feedback: "This gives a clear reason to disagree, or to agree only partly." },
      { id: "quality", core: true, text: "Universities need stable funding to maintain teaching quality.", answer: "could", feedback: "This could help, but the writer needs to explain who would pay if students did not." },
      { id: "formats", core: true, text: "University courses commonly include lectures, seminars and independent study.", answer: "topic", feedback: "This is about university, but it does not address whether tuition should be free." },
      { id: "course-choice", core: false, text: "University students often choose courses according to their future career goals.", answer: "topic", feedback: "This is a genuine point about students and education, but it does not yet help the writer judge whether university should be free for everyone." },
    ],
    help: [
      "Look at the question again. It asks whether university should be free for everyone.",
      "Now look at the idea. Can it help you say why you agree or disagree?",
      "An idea can be about university but still not help with the question about free tuition.",
      "Example: ‘Many courses include lectures’ is about university, but it does not tell us whether tuition should be free.",
    ],
  },
  b2: {
    idea: "Free university education could improve access for students from lower-income families.",
    prompt: "Now read the next sentence. What does it add?",
    shuffle: true,
    labels: [
      { id: "why", text: "Explains why or how" },
      { id: "result", text: "Adds a result" },
      { id: "repeat", text: "Mostly repeats" },
      { id: "direction", text: "Starts another direction" },
    ],
    options: [
      { id: "barrier", text: "High fees may prevent capable students from applying or attending, even when they meet the academic requirements.", answer: "why", feedback: "This explains why cost can stop some students. It identifies the barrier behind the original idea." },
      { id: "income", text: "Removing tuition costs could therefore make family income less important in deciding who can enter higher education.", answer: "result", feedback: "This adds a likely result of removing tuition fees." },
      { id: "debt", text: "It could also make attendance more practical for students who would otherwise avoid large debts.", answer: "why", feedback: "This gives another reason why fees can affect access: some students may avoid debt." },
      { id: "repeat", text: "Therefore, free university would improve access for lower-income students.", answer: "repeat", feedback: "This stays relevant, but it mostly says the first idea again without showing why or how." },
      { id: "outcome", text: "Students who attend university may improve their employment opportunities after graduation.", answer: "direction", feedback: "This starts another possible argument about the benefits of university. It would need a clearer connection to the claim about access." },
    ],
    help: [
      "Look at the first sentence. The main idea is that free university could help more lower-income students attend.",
      "Now look at the next sentence. Does it tell us why, show what happens next, repeat the idea, or start another idea?",
      "For example, ‘High fees may stop capable students from applying’ explains why cost can affect access.",
      "New example: Public transport can reduce traffic. Why? More people can travel without using their own cars.",
    ],
  },
  b3: {
    positions: ["I agree", "I mostly agree", "I mostly disagree", "I disagree", "I want to write my position differently"],
    ideas: [
      { id: "access", text: "Free tuition can widen access for students with limited family income." },
      { id: "public-money", text: "Universal free tuition can place a large demand on public money." },
      { id: "targeted", text: "Targeted financial help may be fairer than paying tuition for every student." },
    ],
    whys: [
      { id: "fees-barrier", idea: "access", text: "High fees can prevent capable students from attending." },
      { id: "debt-risk", idea: "access", text: "Some students may avoid higher education because they fear long-term debt." },
      { id: "other-services", idea: "public-money", text: "Governments also need to fund schools, health services, roads and other public systems." },
      { id: "wealthy-benefit", idea: "targeted", text: "Universal funding would also pay for students whose families can afford the fees." },
    ],
    supports: [
      { id: "income-access", idea: "access", text: "As a result, family income may have less influence on access to higher education." },
      { id: "hypothetical", idea: "access", text: "For example, a capable student from a low-income family may decide not to apply when the fees are unaffordable." },
      { id: "tradeoff", idea: "public-money", text: "This could leave less funding for public services that benefit a wider population." },
      { id: "target-help", idea: "targeted", text: "Directing support towards students who need it could widen access while limiting the public cost." },
      { id: "enough", idea: "all", text: "My reason is clear enough for this planning note; I do not need another step." },
    ],
  },
  b4: {
    prompt: "Does this paragraph explain the idea clearly?",
    shuffle: true,
    options: [
      { id: "reasoning", text: "Free tuition could widen access because high fees may prevent capable students from attending. Removing this cost would mean family income has less influence on who can continue into higher education.", answer: "strong", feedback: "This gives a clear reason, then shows what could happen as a result." },
      { id: "repeat", text: "Free tuition improves access. When tuition is free, access becomes better, so more students have improved access to university.", answer: "weak", feedback: "The sentences remain relevant, but they mostly repeat ‘access improves’ without explaining why." },
      { id: "authority", text: "A 2025 study from a well-known university found that 87% of students succeed when tuition is free. This proves that free university education improves access.", answer: "weak", feedback: "The source and statistic have been invented to make the claim sound convincing. They also discuss success rather than explaining how tuition affects access." },
      { id: "alternative", text: "Free tuition may reduce students’ fear of debt, so they may feel able to consider university and a wider choice of courses.", answer: "could", feedback: "The point about debt could help. It needs a clearer link to students who cannot afford the fees." },
    ],
    help: [
      "Read the first sentence. What is the main idea?",
      "Now read the next sentence. Does it help you understand why the idea is true or what happens because of it?",
      "A longer paragraph can still repeat the same point. A number or study does not help if it is invented or answers a different question.",
      "New example: Exercise can improve health. ‘Regular movement can strengthen the heart’ explains why. ‘Exercise is healthy because it improves health’ mostly repeats.",
    ],
  },
  b5: {
    help: [
      "What is the one main idea of this paragraph?",
      "Now explain why it happens or what happens because of it.",
      "A real example shows the idea in one specific case. Another reason or result adds a new point; it is not an example.",
      "Free tuition could widen access because high fees may prevent capable students from attending even when they meet the academic requirements. For example, a student from a family with limited income may decide not to apply if the cost would create debt they cannot manage. Removing this barrier would make family income less important in determining who can continue into higher education.",
    ],
    aiFeedback: {
      stage: "one Task 2 body paragraph",
      taught: ["The paragraph should make a useful contribution to the answer.", "Explain and support the main idea sufficiently.", "Support may be reasoning, consequence, comparison, clarification, a realistic situation or example.", "Close when the idea's argumentative work is complete."],
      criteria: ["contribution to answering the question", "clarity of the main idea", "explanation", "sufficient relevant support", "irrelevance or repetition", "understandable reasoning", "clear language"],
      exclusions: ["Do not score the whole essay.", "Do not demand an introduction, conclusion or other body paragraph.", "Do not require a statistic, an example, difficult vocabulary or a special linking sentence."],
    },
  },
  w1: {
    tasks: [
      { id: "views", instruction: "Discuss both views and give your own opinion.", required: ["view-a", "view-b", "position"], jobs: [{ id: "view-a", text: "Discuss the first view" }, { id: "view-b", text: "Discuss the other view" }, { id: "position", text: "Make the writer's own view clear" }, { id: "causes", text: "Explain what caused the disagreement" }] },
      { id: "problem", instruction: "What problems does this cause and what solutions can you suggest?", required: ["problems", "solutions"], jobs: [{ id: "problems", text: "Explain the problems" }, { id: "solutions", text: "Suggest ways to solve them" }, { id: "position", text: "Say whether the situation is positive or negative" }, { id: "causes", text: "Explain why the situation has become more common" }] },
      { id: "outweigh", instruction: "Do the advantages outweigh the disadvantages?", required: ["advantages", "disadvantages", "judgement"], jobs: [{ id: "advantages", text: "Explain the advantages" }, { id: "disadvantages", text: "Explain the disadvantages" }, { id: "judgement", text: "Say which side is stronger" }, { id: "solutions", text: "Suggest how to solve the disadvantages" }] },
    ],
    help: [
      "Look at the words that tell the writer what to do.",
      "Choose only the things this question asks for. A different Task 2 question may ask for causes, solutions or an opinion.",
      "Example: ‘Discuss both views and give your opinion’ asks for the first view, the second view and what you think.",
    ],
  },
  w2: {
    shuffle: true,
    options: [
      { id: "reliable", label: "Plan A", text: "Introduction: mostly agree. Body 1: explain how fees restrict access. Body 2: explain why help for students who need it may be more practical than paying for everyone. Conclusion: give the same main answer again.", status: "works", feedback: "The two main paragraphs have different clear ideas, and the answer stays the same from beginning to end." },
      { id: "alternative", label: "Plan B", text: "Introduction: disagree with free tuition for everyone. Body 1: explain pressure on public money. Body 2: explain why grants may be fairer. Body 3: answer the argument for free access. Conclusion: finish the answer.", status: "could", feedback: "This can work if the writer has time to explain all three main ideas. Five paragraphs are not automatically wrong." },
      { id: "thin", label: "Plan C", text: "Introduction. Body 1: access, debt, jobs, university buildings and social life. Body 2: taxes, hospitals, schools, fairness and research. Conclusion.", status: "weak", feedback: "There are too many ideas to explain clearly in the available time." },
      { id: "overlap", label: "Plan D", text: "Introduction: mostly agree. Body 1: poorer students cannot afford fees. Body 2: students with little money may not attend. Conclusion: government should help students.", status: "could", feedback: "The two main paragraphs repeat the same idea. The writer could combine them and add a different idea needed by the answer." },
    ],
  },
  w3: {
    progression: [
      { id: "coherent", text: "Body 1 explains how fees restrict access. Body 2 explains the public cost and why help could go to students who need it most.", viable: true, feedback: "The paragraphs add two different ideas to one clear answer." },
      { id: "repeat", text: "Body 1 explains that fees restrict poorer students. Body 2 explains again that students without money cannot pay fees.", viable: false, feedback: "Different wording does not move the answer forward when the contribution is essentially repeated." },
      { id: "underdeveloped", text: "Body 1 explains how fees restrict access. Body 2 lists the costs of staff, libraries and technology but does not connect these costs to who should pay tuition.", viable: false, feedback: "Both paragraphs are about the topic, but the second does not explain how the costs change the answer." },
    ],
    consistency: [
      { id: "qualify", text: "Explain the concern about public cost, then show why help should go to students who need it most.", viable: true, feedback: "This includes the concern about cost but keeps the writer's main answer clear." },
      { id: "opposite", text: "Use the second paragraph to argue that free tuition is always unfair, without explaining how this fits the earlier mostly-agree position.", viable: false, feedback: "This creates a different position rather than developing or carefully limiting the position already stated." },
      { id: "unclear-balance", text: "Present access and public cost as equally important, then leave the reader to decide what the writer believes.", viable: false, feedback: "Both ideas can be relevant, but this does not keep the required personal position clear." },
    ],
    help: [
      "Say in simple words what each paragraph does.",
      "Do the two paragraphs add different useful ideas, or do they say the same thing twice?",
      "Now check the writer's answer. Does the second paragraph still fit what the writer said at the beginning?",
    ],
  },
  w4: {
    bodyPlan: "The essay mostly agrees that costs should not block capable students, but argues that financial help for students who need it is more practical than paying the fees of every student.",
    conclusions: [
      { id: "close", text: "In conclusion, tuition costs should not prevent capable students from entering university, but targeted financial support is a more practical policy than making every course free for everyone.", viable: true, feedback: "This clearly closes the partly-agree answer developed in the essay." },
      { id: "incomplete", text: "In conclusion, university fees can create serious barriers for capable students.", viable: false, feedback: "This is relevant and clear, but it closes only the access idea and leaves out the writer's judgement about targeted rather than universal support." },
      { id: "reader", text: "In conclusion, you should help students who cannot pay, but you should not make university free for everybody.", viable: false, feedback: "The main judgement fits, but direct advice to ‘you’ sounds more like a conversation with the reader than an essay conclusion. It could work after a style change." },
      { id: "formal", text: "In conclusion, the allocation of targeted financial assistance represents a preferable policy to the universal removal of tuition charges.", viable: false, feedback: "The judgement broadly fits, but the wording is more formal and indirect than necessary. Clearer natural English would communicate it more efficiently." },
      { id: "stronger", text: "In conclusion, university education should be completely free for every student, despite the pressure this may place on public funding.", viable: false, feedback: "This changes the writer's partly-agree position into complete agreement." },
    ],
    help: [
      "For the introduction, tell the reader what the essay is about. Because this question asks what you think, make your answer clear too.",
      "A simple opening can work: ‘Some people believe university should be free. I mostly agree, but I think support should go to students who need it most.’",
      "For the conclusion, read the answer above the choices. Does each choice finish the same answer, or miss or change something?",
      "The best conclusion includes access and targeted support in clear, natural English.",
    ],
  },
  c1: {
    paragraphs: [
      { id: "intro", label: "Introduction", text: "University tuition can create a serious barrier for some students. Although I agree that governments should widen access, I do not believe every student should automatically receive free tuition.", issue: false },
      { id: "access", label: "Body paragraph 1", text: "The strongest reason for public support is that high fees can prevent capable students from attending. A student from a low-income family may meet every academic requirement but decide not to apply because the cost would create unmanageable debt. Targeted funding can reduce this barrier and make access depend less on family income.", issue: false },
      { id: "funding", label: "Body paragraph 2", text: "On the other hand, universities need stable funding because education is important. Furthermore, governments spend money on many services, and university courses can be expensive to provide. This is a significant issue for modern society.", issue: true },
      { id: "conclusion", label: "Conclusion", text: "In conclusion, university should be completely free for every student because this is the fairest approach.", issue: true },
    ],
  },
  c2: {
    shuffle: true,
    options: [
      { id: "position", text: "Make the conclusion match the ‘partly agree’ answer in the rest of the essay.", priority: 1, feedback: "This changes the whole answer. At the moment, the reader receives two different answers." },
      { id: "develop", text: "Explain how the cost to the government affects the choice between free tuition and help for students who need it.", priority: 2, feedback: "This is the next important problem. The writer mentions the cost but does not explain how it changes the answer." },
      { id: "word", text: "Replace the clear word ‘important’ with ‘significant’.", priority: 4, feedback: "This changes appearance more than meaning and should not take priority over the answer and reasoning." },
      { id: "punctuation", text: "Correct one small punctuation mistake.", priority: 3, feedback: "Punctuation matters, but this small mistake has less effect than the changed answer and the unexplained main idea." },
      { id: "connector", text: "Use ‘However’ to make the move from access to the funding concern clearer.", priority: 3, feedback: "This could help the reader notice the contrast later, but it cannot replace the missing explanation of why funding affects the tuition judgement." },
    ],
    help: [
      "First look for a problem that changes the writer's main answer.",
      "Compare the answer in the introduction with the answer in the conclusion. Are they the same?",
      "Fix the changed answer first. Then improve the paragraph about funding. Small word and punctuation changes can come later.",
    ],
  },
  teachingExample: {
    paragraphs: [
      "University fees can prevent some capable students from continuing their education. Although I agree that financial barriers should be reduced, I believe targeted public support is more practical than making every university course free for every student.",
      "Students from lower-income families may decide not to apply when tuition would create debt they cannot manage. This means academic ability is not the only factor determining access. Grants or reduced fees for these students can therefore make higher education more accessible without requiring them to take an unreasonable financial risk.",
      "However, universities also need reliable funding for teaching, facilities and student services. If governments paid every student's fees, including those whose families can afford them, less public money might remain for schools, healthcare or targeted university grants. Concentrating support on students who face a genuine financial barrier could protect access while using public funds more carefully.",
      "In conclusion, cost should not prevent capable students from attending university, but targeted support offers a fairer and more sustainable solution than universal free tuition.",
    ],
    lenses: [
      { id: "task", label: "Task Response", note: "The writer partly agrees, develops access and public-cost reasoning, and keeps the same position throughout." },
      { id: "coherence", label: "Coherence and Cohesion", note: "Each paragraph makes a distinct contribution, and the contrast follows from the reasoning rather than from connectors alone." },
      { id: "lexical", label: "Lexical Resource", note: "Words such as ‘financial barrier’, ‘targeted support’ and ‘public funds’ are precise and natural without being decorative." },
      { id: "grammar", label: "Grammatical Range and Accuracy", note: "Sentence forms vary where useful, while relationships remain clear and controlled." },
    ],
  },
  ai: {
    introduction: {
      stage: "Writing Task 2 introduction",
      taught: ["Answer the exact question rather than a memorised question type.", "Make the learner's position clear when the question asks for one.", "Show the direction of the essay without developing the full argument in the introduction.", "Accept more than one clear and defensible introduction."],
      criteria: ["whether the introduction responds to both parts of the question", "whether the learner's positive or negative judgement is clear", "whether the two planned paragraph directions are represented clearly", "whether the language communicates the intended meaning"],
      exclusions: ["Do not give a band score or claim to be an official IELTS examiner.", "Do not immediately rewrite the introduction.", "Do not demand a memorised template, difficult vocabulary, statistics, examples or a fixed sentence count.", "Use the minimum necessary intervention: prompt, then hint, then explain, and model only if more help is needed."],
    },
    fullEssay: {
      stage: "complete Task 2 essay",
      taught: ["Answer the exact instruction and complete every required job.", "Maintain a clear and consistent position when required.", "Use paragraphs with useful contributions and clear progression.", "Explain and support relevant main ideas.", "Use clear, natural and controllable language."],
      criteria: ["Task Response: task coverage, position, relevance and development", "Coherence and Cohesion: organisation, paragraph contribution, progression, repetition and useful linking", "Lexical Resource: clear, appropriate, natural and sufficiently varied word choice", "Grammatical Range and Accuracy: clear meaning, controlled variety and recurring problems that affect communication"],
      exclusions: ["Do not give a band score or claim to be an official IELTS examiner.", "Do not immediately rewrite the essay.", "Do not demand advanced vocabulary, a statistic, an example, four paragraphs or exactly two main ideas.", "Do not correct every sentence indiscriminately.", "Do not treat reaching 250 words as proof of quality; below 250, identify the requirement calmly and diagnose what may need development."],
    },
    revision: {
      stage: "revision of a complete Task 2 essay",
      taught: ["Revision should improve a chosen problem in the learner's existing response.", "Judge whether the current revision makes the intended meaning, reasoning, organisation or language clearer.", "Prioritise the learner's selected revision goal before starting any broader critique."],
      criteria: ["whether the chosen revision priority improved", "whether the change preserved useful parts of the original", "the most important remaining issue connected to that priority", "a concrete next revision the learner can make"],
      exclusions: ["Do not restart a complete first-pass essay review unless a serious problem makes that necessary.", "Do not give a band score or claim to be an official IELTS examiner.", "Do not rewrite the essay or provide a corrected version immediately.", "Do not demand advanced vocabulary, extra features or changes unrelated to the selected priority."],
    },
    transfer: {
      stage: "independent Task 2 transfer essay",
      taught: ["The instruction asks for advantages and disadvantages, not a personal opinion or an outweigh judgement.", "Answer both required jobs.", "Develop relevant contributions with explanation and support.", "Organise the answer clearly and close it without starting a new argument."],
      criteria: ["Task Response: coverage of both advantages and disadvantages without forcing an unrequested judgement", "Coherence and Cohesion: useful paragraph contributions and progression", "Lexical Resource: clear and appropriate wording", "Grammatical Range and Accuracy: clear meaning and useful priorities"],
      exclusions: ["Do not give a band score or claim to be an official IELTS examiner.", "Do not require a personal opinion, an outweigh judgement, a fixed paragraph count, difficult vocabulary or invented evidence.", "Do not immediately rewrite or correct every sentence.", "Do not treat 250 words as a quality score or block diagnosis below it."],
    },
  },
};
