const{chromium}=require('playwright'),assert=require('node:assert/strict');const base='http://localhost:8000/listening/day-4/',api='http://127.0.0.1:8789';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),errors=[];async function client(){const ctx=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});await ctx.route('**/shared/classroom/config.js',r=>r.fulfill({contentType:'application/javascript',body:`export const serviceURL='${api}';`}));await ctx.route('**/day-4/release-config.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('serviceReady=false','serviceReady=true')});});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));return p;}
const t=await client(),a=await client(),b=await client();await t.goto(base+'teacher-control/');await t.locator('#create-class').click();await t.locator('#teacher-session').waitFor();const code=(await t.locator('#classroom-code').innerText()).trim();assert.equal(await t.locator('[data-release]').count(),12);
for(const p of[a,b]){await p.goto(base);assert.equal(await p.locator('section.activity').count(),18);await p.locator('#class-code').fill(code);await p.locator('#class-connect-form button').click();await p.getByText('Connected ✓',{exact:true}).waitFor();await p.locator('#l48-31').fill('water');await p.locator('[data-activity=l48]').evaluate(f=>f.requestSubmit());assert.equal(await p.locator('#l48 .result').innerText(),'');assert.equal(await p.locator('.transcript-reading').count(),2);assert.equal(await p.locator('audio,video,textarea').count(),0);assert.equal(await p.locator('form[data-activity] input:disabled,form[data-activity] select:disabled').count(),0);assert(await p.locator('#ai44 form').isVisible());}
await t.locator('[data-release=local48]').click();await a.waitForTimeout(300);assert.equal(await a.locator('.transcript-reading').count(),2);assert(!await a.locator('[data-answer-check=local48]').isVisible());
await a.context().setOffline(true);await a.locator('#l47-31').fill('public');await t.locator('[data-release=l48]').click();await b.locator('[data-answer-check=l48]').waitFor();await a.context().setOffline(false);await a.locator('[data-answer-check=l48]').waitFor();assert.equal(await a.locator('#l47-31').inputValue(),'public');assert(!await a.locator('[data-answer-check=l47]').isVisible());
await t.locator('#release-all').click();await a.locator('[data-answer-check=l47]').waitFor();
const keys={l41:['emission levels','environment','health','issues'],l42:['concentration','shorter','subjects'],l43:['information','printed','minutes'],l44:['4','1','3','2'],l45:['A','B','C'],l46:['4','1','3','2'],l47:['public','processing','formations','energy','waste materials','land','costs','intervals','30%','expensive'],l48:['water','corrode','limestone','small','capsules','A','D','C','F','G'],local47:['A','B','C','B','A','C','B','A'],pattern47:['A','C','B'],local48:['B','A','A','B','A','C','B','C'],pattern48:['B','A','C']};
for(const[id,key]of Object.entries(keys)){for(const[i,value]of key.entries()){const number=['l47','l48'].includes(id)?31+i:1+i;const f=a.locator(`[name="${id}-${number}"]`);if(await f.first().evaluate(e=>e.tagName==='SELECT'))await f.selectOption(value);else if(await f.first().getAttribute('type')==='radio')await a.locator(`[name="${id}-${number}"][value="${value}"]`).check();else await f.fill(value);}if(id==='pattern48')assert.equal(await a.locator('.comparison').count(),0);await a.locator(`[data-answer-check=${id}]`).click();assert((await a.locator(`#${id} .result`).innerText()).startsWith(`${key.length} / ${key.length}`),id);}
assert.equal(await a.locator('#l44 select').count(),4);assert.equal(await a.locator('#l44').getByText('1. Sceptical',{exact:true}).count(),1);assert(!/Controversial|Skeptical/.test(await a.locator('#l44').innerText()));assert(await a.locator('#l44-2 option[value="4"]').isDisabled());await a.locator('#l44-1').selectOption('');assert(!await a.locator('#l44-2 option[value="4"]').isDisabled());await a.locator('#l44-1').selectOption('4');await a.locator('[data-answer-check=l44]').click();
await a.locator('#ai44 input[value=C]').check();assert.equal(await a.locator('#ai44 [data-answer-check]').count(),0);assert.equal(await a.locator('#ai44 .result').innerText(),'');assert.equal(await a.locator('#read47 [data-highlight]').count(),12);assert.equal(await a.locator('#read48 [data-highlight]').count(),11);assert.equal(await a.locator('.comparison').count(),1);assert.equal(await a.locator('[data-say],[data-model]').count(),0);
for(const id of['local47','pattern47','local48','pattern48']){const evidence=a.locator(`#${id} details.evidence`).first();await evidence.locator('summary').click();assert(await evidence.locator('.transcript-reading').isVisible());}
const rendered=await a.evaluate(async()=>{const{transcripts}=await import('./transcripts.js');const clean=s=>s.replace(/\s+/g,' ').trim();return ['petroleum','concrete'].map((kind,i)=>{const words=[...document.querySelectorAll(`#read${i?48:47} .transcript-words`)].map(el=>{const copy=el.cloneNode(true);copy.querySelectorAll('.phrase-number').forEach(n=>n.remove());return copy.textContent;});return clean(words.join(' '))===clean(transcripts[kind].paragraphs.join(' '));});});assert.deepEqual(rendered,[true,true]);
const fs=require('node:fs');for(const [id,file] of [['read47','4.7'],['read48','4.8']]){let source=fs.readFileSync(`listening/day-4/source/audio-script-${file}.txt`,'utf8');if(file==='4.7')source=source.replace(/^youthful, intelligent London accent\]\s*\n/,'').replace(/\[(?:short|long) pause\]/g,'');const actual=await a.locator(`#${id} .transcript-words`).evaluateAll(els=>els.map(el=>{const c=el.cloneNode(true);c.querySelectorAll('.phrase-number').forEach(n=>n.remove());return c.textContent;}).join(' '));const clean=x=>x.replace(/\s+/g,' ').trim();assert.equal(clean(actual),clean(source),id+' rendered vs definitive TXT');assert(!/\[(short|long) pause\]|London accent/.test(actual));assert.equal(await a.locator(`#${id} strong[data-highlight]`).count(),file==='4.7'?12:11);}

for(const[id,number,cases]of[['l41',1,[['emissions',true],['emission levels',true],['emission',false]]],['l47',35,[['waste materials',true],['waste',false]]],['l47',36,[['land',true],['farmland',false]]],['l47',38,[['intervals',true],['schedule',false]]],['l47',39,[['30%',true],['30',false]]]]){for(const[value,right]of cases){await a.locator(`#${id}-${number}`).fill(value);await a.locator(`[data-answer-check=${id}]`).click();assert.equal(await a.locator(`[data-feedback="${id}-${number}"]`).evaluate(e=>e.classList.contains('correct')),right);}await a.locator(`#${id}-${number}`).fill(cases[0][0]);await a.locator(`[data-answer-check=${id}]`).click();}
await a.locator('#l48-31').fill('the water');assert.equal(await a.locator('#read48 .transcript-reading').count(),1);assert.equal(await a.locator('.comparison').count(),0);await a.locator('[data-answer-check=l48]').click();assert((await a.locator('#l48 .result').innerText()).startsWith('9 / 10'));await a.locator('#l48-31').fill('water');await a.locator('[data-answer-check=l48]').click();
await a.reload();await a.locator('#l48 .result').filter({hasText:'10 / 10'}).waitFor();assert.equal(await a.locator('#l44-1').inputValue(),'4');assert(await a.locator('#ai44 input[value=C]').isChecked());assert.equal(await a.locator('#read48 [data-highlight]').count(),11);await b.reload();await b.getByText('Connected ✓',{exact:true}).waitFor();assert.equal(await b.locator('#l48-31').inputValue(),'water');assert.equal(await b.locator('.transcript-reading').count(),2);
assert.equal((await a.request.post(`${api}/v1/classes/${code}/release?workshop=listening-day-4`,{headers:{Authorization:'Bearer '+code},data:{all:true}})).status(),403);assert.equal((await a.request.get(`${api}/v1/classes/${code}?workshop=listening-day-3`)).status(),409);
await a.locator('img').evaluateAll(imgs=>Promise.all(imgs.map(i=>{i.loading='eager';return i.decode()})));for(const width of[360,390,430,1280]){await a.setViewportSize({width,height:900});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await a.locator('#read47').evaluate(e=>e.scrollIntoView({behavior:'instant'}));await a.screenshot({path:`/tmp/day4-analysis-${width}.png`});await t.setViewportSize({width,height:900});assert(await t.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}assert.deepEqual(errors,[]);await browser.close();console.log('PASS analytical Day4: 18 sections / 12 releases; every key; exclusive speaker dropdowns; unscored AI; full verbatim rendered transcripts; evidence; leak guards; persistence/offline; mobile/desktop.');})().catch(e=>{console.error(e);process.exit(1)});
