const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const {execFileSync}=require('node:child_process');
const base=process.env.READING_PREVIEW_URL||'http://localhost:8000/reading/day-1/';
const key='ielts-reading-day-1-v1';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 await context.addInitScript(()=>{const seed=sessionStorage.getItem('luxury-test-seed');if(seed){localStorage.setItem('ielts-reading-day-1-v1',seed);sessionStorage.removeItem('luxury-test-seed')}});
 const page=await context.newPage(),errors=[],failed=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)failed.push(r.url())});
 await page.goto(base);
 const meta=await page.evaluate(async()=>{const a=await import('./day-1.js'),b=await import('./luxury.js'),c=await import('./luxury-content.js'),d=await import('./continuation.js');return {titles:a.screens.map(s=>s.title),stages:b.luxuryStages,tasks:b.luxuryTasks,content:c.luxury,previous:d.continuationStages.map(s=>s.title)}});
 const prior=execFileSync('git',['show','HEAD:reading/day-1/day-1.js'],{encoding:'utf8'});const titles=[...prior.matchAll(/add\(\d+,'([^']*)'/g)].map(m=>m[1]);titles.splice(22,0,...meta.previous);
 assert.equal(titles.length,41);assert.deepEqual(meta.titles.slice(0,41),titles);assert.equal(meta.titles.length,49);assert.equal(meta.titles[36],'You Are What You Eat—Or Are You?');assert.equal(meta.titles[41],meta.content.ferrari.title);assert.equal(meta.titles[44],meta.content.amouage.title);
 const start=async(id,extra={})=>{const n=typeof id==='number'?id:41+meta.stages.findIndex(s=>s.id===id);await page.evaluate(({key,n,extra})=>{const saved=JSON.parse(localStorage.getItem(key)||'{}');sessionStorage.setItem('luxury-test-seed',JSON.stringify({...saved,sequenceVersion:2,step:n,...extra}));},{key,n,extra});await page.reload();await page.locator('h1').waitFor();};
 const taskPane=async()=>{if(await page.locator('.luxury .c-mobile-tabs').isVisible())await page.locator('[data-l-pane=task]').click();};
 const noOverflow=async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('.luxury .c-pane:visible').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.clientWidth+1)));};
 // Existing sequence and saved states stay at precisely the same indices.
 for(const n of [16,21,22,29,36,39,40]){await start(n,{notes:{reflection:'Keep my reflection'},answers:{'heading-bedouin-0':[3]}});assert.equal(await page.locator('h1').innerText(),titles[n]);await page.reload();assert.equal(await page.locator('h1').innerText(),titles[n]);assert.equal(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).notes.reflection,key),'Keep my reflection');}
 // Every appended screen is traversable without answers or opening optional support.
 for(const width of [1440,1280,768,390,360,320]){await page.setViewportSize({width,height:900});await start(39,{luxury:{}});for(let n=39;n<49;n++){assert.equal(await page.locator('h1').innerText(),meta.titles[n]);await noOverflow();if(n>=41){const task=meta.tasks[meta.stages[n-41].id];assert.equal(await page.locator('[data-l-check]').count(),task?1:0);assert.equal(await page.locator('[data-check],[data-answer],[data-c-check]').count(),0);}if(n<48){assert(await page.locator('#next').isEnabled());await page.locator('#next').click();}else assert(!await page.locator('#next').isVisible());}}
 await page.setViewportSize({width:1440,height:1000});
 for(const [id,name]of [['ferrari-summary','ferrari'],['amouage-scan','amouage']]){await start(id);assert.deepEqual(await page.locator('.c-passage-pane .passage').allInnerTexts(),meta.content[name].paragraphs);for(let i=0;i<meta.content[name].paragraphs.length;i++){await page.locator(`[data-l-paragraph="${i}"]`).click();assert(await page.locator(`[data-l-paragraph-text="${i}"]`).isVisible());}}
 async function fill(task,mode='correct'){
  for(const [i,item] of task.items.entries()){
   const id=task.id+'-'+i;
   if(item.accepted)await page.locator(`[name="${id}"]`).fill(mode==='correct'?item.answer:'Not sure');
   else if(task.kind==='summary')await page.locator(`[name="${id}"][value="${mode==='correct'?item.answer:item.options.find(o=>o.value!==item.answer).value}"]`).check();
   else await page.locator(`[name="${id}"]`).selectOption(mode==='correct'?item.answer:'?');
  }
 }
 let checked=0;
 for(const task of Object.values(meta.tasks)){
  await start(task.id,{luxury:{}});assert(!await page.locator('.c-results').isVisible());assert.equal(await page.locator('[data-l-check]').count(),1);
  assert(await page.locator('.c-task').evaluate(f=>!!(f.querySelectorAll('.c-item')[f.querySelectorAll('.c-item').length-1].compareDocumentPosition(f.querySelector('[data-l-check]'))&Node.DOCUMENT_POSITION_FOLLOWING)));
  await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-check-notice').innerText(),/Attempt all/);assert(!await page.locator('.c-results').isVisible());
  await fill(task,'wrong');await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-result-summary').innerText(),/^0 \//);
  await fill(task);assert(!await page.locator('.c-results').isVisible());await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-result-summary').innerText(),new RegExp('^'+task.items.length+' / '+task.items.length));
  for(let i=0;i<task.items.length;i++){const result=page.locator('.c-result').nth(i);assert(!await result.locator('blockquote').isVisible());await result.locator('summary').click();assert.equal(await result.locator('blockquote').innerText(),task.items[i].evidence);assert((await result.innerText()).includes(task.items[i].rationale));}
  await page.reload();assert.match(await page.locator('.c-result-summary').innerText(),new RegExp('^'+task.items.length+' / '+task.items.length));checked+=task.items.length;
 }
 assert.equal(checked,28);
 // Precisely retrieved lexical units, not semantic alternatives; no lenient grading.
 await start('amouage-completion');await fill(meta.tasks['amouage-completion']);
 for(const [i,bad]of [[0,'clientele'],[1,'identity'],[4,'culture'],[5,'place'],[5,'Oman'],[3,'14 weeks'],[1,'recognisable creative identity']]){await page.locator(`#amouage-completion-${i}`).fill(bad);await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-result').nth(i).innerText(),/Compare your answer/);if(bad.split(' ').length>2)assert.match(await page.locator('.c-result').nth(i).innerText(),/exceeds the two-word limit/);await page.locator(`#amouage-completion-${i}`).fill(meta.tasks['amouage-completion'].items[i].answer);}
 for(const [i,q]of meta.tasks['amouage-completion'].items.entries())await page.locator(`#amouage-completion-${i}`).fill('  '+q.answer.toUpperCase()+'  ');await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-result-summary').innerText(),/^6 \/ 6/);
 await start('amouage-scan');await fill(meta.tasks['amouage-scan']);await page.locator('#amouage-scan-2').fill('myrrh');await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-result').nth(2).innerText(),/Compare your answer/);await page.locator('#amouage-scan-2').fill('Frankincense');await page.locator('#amouage-scan-3').fill('14 weeks');await page.locator('#amouage-scan-4').fill('6 months');await page.locator('[data-l-check]').click();assert.match(await page.locator('.c-result-summary').innerText(),/^5 \/ 5/);
 // One claim at a time, reversible progression, saved note and final optional comparison.
 await start('ferrari-nuance',{luxury:{}});assert.equal(await page.locator('.l-nuance-claim').count(),1);await page.locator('[data-l-note]').fill('Some became all.');for(let i=0;i<4;i++){assert.equal(await page.locator('.l-nuance-claim').innerText(),meta.content.ferrari.nuance[i]);if(i<3){assert.equal(await page.locator('.c-task-pane details').count(),0);await page.locator('[data-l-nuance="1"]').click();}}await page.locator('.c-task-pane summary').click();assert.match(await page.locator('.c-task-pane').innerText(),/developed from something partly true/);await page.reload();assert.equal(await page.locator('.l-nuance-claim').innerText(),meta.content.ferrari.nuance[3]);assert.equal(await page.locator('[data-l-note]').inputValue(),'Some became all.');await page.locator('[data-l-nuance="-1"]').click();assert.equal(await page.locator('.l-nuance-claim').innerText(),meta.content.ferrari.nuance[2]);
 await start('ferrari-bridge');assert.equal(await page.locator('.luxury blockquote').innerText(),meta.content.ferrari.bridge);await page.locator('.luxury summary').click();for(const idea of meta.content.ferrari.bridgeIdeas)assert((await page.locator('.luxury').innerText()).includes(idea));await page.locator('#next').click();assert.equal(await page.locator('h1').innerText(),meta.content.amouage.title);
 // Mobile comparison keeps both pane positions and input after switching/reload.
 for(const width of [390,360]){await page.setViewportSize({width,height:844});await start('amouage-endings',{luxury:{}});await page.locator('.c-passage-pane').evaluate(e=>{e.scrollTop=670;e.dispatchEvent(new Event('scroll'))});const pt=await page.locator('.c-passage-pane').evaluate(e=>e.scrollTop);await taskPane();await page.locator('#amouage-endings-2').selectOption('A');await page.locator('.c-task-pane').evaluate(e=>{e.scrollTop=330;e.dispatchEvent(new Event('scroll'))});const qt=await page.locator('.c-task-pane').evaluate(e=>e.scrollTop);await page.locator('[data-l-pane=passage]').click();assert(Math.abs(await page.locator('.c-passage-pane').evaluate(e=>e.scrollTop)-pt)<3);await page.locator('[data-l-pane=task]').click();assert(Math.abs(await page.locator('.c-task-pane').evaluate(e=>e.scrollTop)-qt)<3);await page.reload();assert(await page.locator('.c-task-pane').isVisible());assert(Math.abs(await page.locator('.c-task-pane').evaluate(e=>e.scrollTop)-qt)<3);assert.equal(await page.locator('#amouage-endings-2').inputValue(),'A');await noOverflow();await page.locator('.c-task-pane').evaluate(e=>e.scrollTop=0);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:`/tmp/luxury-mobile-${width}.png`,fullPage:true});await page.locator('[data-l-pane=passage]').click();assert(Math.abs(await page.locator('.c-passage-pane').evaluate(e=>e.scrollTop)-pt)<3);}
 await page.setViewportSize({width:1440,height:1000});await start('amouage-completion',{luxury:{}});await page.locator('#amouage-completion-0').focus();await page.keyboard.type('discerning clientele');await page.keyboard.press('Tab');assert.equal(await page.locator('#amouage-completion-0').inputValue(),'discerning clientele');await fill(meta.tasks['amouage-completion']);await page.locator('[data-l-check]').focus();await page.keyboard.press('Enter');assert.match(await page.locator('.c-result-summary').innerText(),/^6 \/ 6/);
 await start('amouage-summary',{luxury:{}});await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'/tmp/luxury-laptop.png',fullPage:true});
 await start('amouage-scan',{luxury:{answers:[],checked:null,positions:{bad:'bad'},notes:null,nuance:900}});await page.locator('[data-l-check]').click();assert(await page.locator('#next').isEnabled());
 const blocked=await browser.newContext({viewport:{width:390,height:844}});await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('Blocked')}}));const bp=await blocked.newPage();bp.on('pageerror',e=>errors.push(e.message));await bp.goto(base);await bp.locator('#menu summary').click();await bp.locator('[data-jump="41"]').click();for(let i=41;i<48;i++)await bp.locator('#next').click();assert.equal(await bp.locator('h1').innerText(),meta.titles[48]);assert.match(await bp.locator('#storage-note').innerText(),/Saving is unavailable/);
 await page.goto(base+'teacher-control/');assert.equal(await page.locator('section').count(),12);const h=await page.locator('section h2').allInnerTexts();assert(h.indexOf('You Are What You Eat—Or Are You?')<h.indexOf(meta.content.ferrari.title));assert(h.indexOf(meta.content.ferrari.title)<h.indexOf(meta.content.amouage.title));const guide=await page.locator('#guide').innerText();assert.match(guide,/STEPS 42–44/);assert.match(guide,/STEPS 45–49/);await page.locator('summary').filter({hasText:'Approved revisions'}).click();for(const r of meta.content.revisions)assert((await page.locator('#guide').innerText()).includes(r.replacement));
 assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);await browser.close();console.log('PASS: 8 appended screens, 6 whole tasks, all 28 answers; fixed prior 41-screen order; 6 widths; wrong/blank/retry/evidence; all rejected alternatives; strict word limit; Ferrari nuance/bridge; mobile positions; keyboard; saved and blocked storage; teacher order; no console/runtime/HTTP errors.');
})().catch(e=>{console.error(e);process.exit(1)});
