import {createDay4Control} from './release-state.js';
import {models,dialogue,reference,topics,finalQuestions} from '../../content/speaking/day-4.js';
import {releaseConfig} from './release-config.js';
import {installStudentRelease} from '../shared/release-control.js';
const key=releaseConfig.progressKeys[0],app=document.getElementById('app');
let state={step:0,answers:{},reveals:{},follow:0,rounds:{}};
try{const v=JSON.parse(localStorage.getItem(key));if(v&&typeof v==='object')state={...state,...v};}catch{}
for(const name of ['answers','reveals','rounds'])if(!state[name]||typeof state[name]!=='object'||Array.isArray(state[name]))state[name]={};
for(const [id,v] of Object.entries(state.answers))state.answers[id]=Array.isArray(v)?v.filter(n=>Number.isInteger(n)&&n>=0&&n<20):[];
state.follow=Number.isInteger(state.follow)?Math.max(0,Math.min(3,state.follow)):0;
let storageOK=true;
const save=()=>{try{localStorage.setItem(key,JSON.stringify(state));storageOK=true;}catch{storageOK=false;}const note=document.getElementById('storage-note');if(note)note.textContent=storageOK?'Choices stay on this device.':'Saving is unavailable. You can still use the whole workshop while this page stays open.';};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const control=createDay4Control(releaseConfig),screens=[];let releaseUI;
const add=(stage,title,body,next='Continue')=>screens.push({stage,title,body,next});
const picked=id=>(state.answers[id]||[])[0];
const para=s=>`<p>${s}</p>`;
const help=(name,body)=>`<details class="help-card"><summary>${name}</summary><div>${body}</div></details>`;
const speech=(text,marks=[])=>{let s=esc(text);for(const m of marks)s=s.replace(esc(m),`<strong>${esc(m)}</strong>`);return `<div class="spoken">${s}</div>`;};
const question=q=>`<blockquote>${esc(q)}</blockquote>`;
const labels=models.map(m=>m.label);
function choices(id,title,options=labels,multi=false){return `<fieldset><legend>${title}</legend><div class="choices">${options.map((o,i)=>`<label class="choice"><input name="${id}" type="${multi?'checkbox':'radio'}" value="${i}" ${(state.answers[id]||[]).includes(i)?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div></fieldset>`;}
function select(id,title,options){return `<label class="select-label" for="${id}">${title}</label><select id="${id}" name="${id}"><option value="">Choose if you like</option>${options.map((o,i)=>`<option value="${i}" ${picked(id)===i?'selected':''}>${esc(o)}</option>`).join('')}</select>`;}
function reveal(id,title,body){return `<button class="reveal-button" data-show="${id}" aria-expanded="${!!state.reveals[id]}" aria-controls="${id}">${title}</button><div class="feedback" id="${id}" ${state.reveals[id]?'':'hidden'}>${body}</div>`;}
const tools=()=>'<div class="tool-list">'+models.map(m=>`<p><strong>${m.label}</strong><small>${m.formal}</small></p>`).join('')+'</div>';
add('think','Think aloud about bigger ideas',()=>'<div class="part-comparison"><p><strong>Part 1</strong>Talk naturally about yourself and familiar things.</p><p><strong>Part 2</strong>Build and sustain one longer response.</p><p><strong>Part 3</strong>Think aloud about bigger ideas.</p></div><p>Part 3 explores more general, abstract ideas connected with Part 2. The examiner controls the discussion through questions.</p>'+help('What might the examiner ask?','<p>Why? Can you explain? What happens because of that? How does it compare? What about the past or future?</p><p>A follow-up may grow from what you have just said. This is not an uncontrolled casual conversation.</p>')+'<p class="principle">Choose a direction → build one idea → make your thinking easy to follow.</p>','Start Day 4');
add('think','Choose a way to think',()=>'<p class="principle">Don’t search for more things to say. Choose a way to think.</p>'+tools()+'<p>These are thinking tools, not answer templates. More than one can fit a question.</p><p>Read the next answers as speech. The pauses are natural; you do not need to copy the fillers.</p>');
models.forEach((m,i)=>add('think','What is the speaker doing?',()=>question(m.question)+speech(m.script,m.marks)+choices('model-'+i,'Choose a thinking tool.')+reveal('model-reveal-'+i,'Reveal the thinking',`<p><strong>${m.label}</strong><br>${m.formal}</p><p>This is the main direction here. Other tools can overlap.</p><p>Useful language from this answer:</p><ul>${m.extract.map(x=>`<li>${x}</li>`).join('')}</ul><p>The phrases help build the thought. You do not need all of them.</p>${i===3?help('Other ways a speaker could compare',speech('Compared with a small town, a city has more jobs. The main difference is the choice you have. Both places can be good to live in, but it depends on what matters to you.',['Compared with','The main difference is','Both','but'])+'<p>These are additional examples, not words taken from the first answer.</p>'):i===4?help('Another possible result',speech('If shops stopped taking cash, some older customers might find shopping harder.',['If','might'])):''}`)));
add('listen','Hear the thinking',()=>'<p>Listen to the audio your teacher plays. Which thinking tool can you hear?</p>'+help('Keep the five tools nearby',tools())+Array.from({length:5},(_,i)=>`<section class="listening-item"><h2>Audio ${i+1}</h2>${select('audio-'+i,'Which thinking tool?',labels)}<p>What did you hear that helped you decide? Tell a partner a phrase or idea.</p>${select('evidence-'+i,'Your evidence',['I can point to a phrase or idea','I’d like to hear it again'])}</section>`).join('')+'<p>No automatic score: compare your evidence with the teacher. Tools may overlap.</p><p class="hint">If playback is unavailable, your teacher can read an earlier spoken example aloud.</p>');
add('listen','These two can look similar',()=>'<section class="contrast"><h2>WHY? → WHAT HAPPENS?</h2><p>I’m explaining a relationship.</p>'+speech('People spend more time sitting at work, so they get less physical activity.',['so'])+'<p class="thinking-path">A happens → B happens</p></section><section class="contrast"><h2>IF… → MAYBE…</h2><p>I’m imagining a situation and its possible result.</p>'+speech('If companies encouraged people to move more during the working day, employees might become more active.',['If','might'])+'<p class="thinking-path">Imagine A → maybe B</p></section>'+reveal('overlap','See how they work together',speech('If more people used public transport, there would be fewer cars on the road, so traffic might improve.',['If','so'])+'<p><strong>IF…</strong> = imagined situation<br><strong>so…</strong> = consequence</p><p>Thinking tools can overlap.</p>'));
add('listen','Transform the thinking',()=>question('Many people drive short distances instead of walking.')+'<p>What happens because of this?</p>'+speech('One effect is…')+'<p>Say your answer aloud.</p>'+reveal('transform','Now imagine a change',speech('If more people walked short distances…')+'<p>Say what might happen. You are changing the situation, not just explaining what happens now.</p>')+'<p>You can practise both aloud with your partner.</p>');
function routes(q,rows){return question(q)+'<p>Open any direction. Say one answer. Then try a different direction if you like.</p>'+rows.map(([i,s])=>help(labels[i],speech(s)+'<p>Build one idea from here, in your own words.</p>')).join('')+'<p class="principle">Same question. Different thinking.</p><p>You do not need to identify one official question type before answering.</p>';}
add('directions','Same question. Different thinking.',()=>routes('Why are fewer young people interested in traditional jobs?',[[0,'Hmm… one reason might be…'],[3,'Compared with their parents’ generation…'],[2,'In the past… but nowadays…']])+help('What if you question the idea?','<p>You can say that this may not be true for every job or every place. Then explain your view.</p>'));
add('directions','Choose another direction',()=>routes('Should cities make it more difficult to use private cars?',[[1,'I can see both sides, actually. The main advantage would be…'],[4,'Well, if cities made driving more difficult, I think…'],[0,'I think one of the biggest problems with private cars is…']]));
add('directions','Don’t add more things. Add more meaning.',()=>question('Why is exercise important?')+'<h2>Answer A</h2>'+speech('In my opinion, exercise is important because it improves people’s physical and mental health. For example, even walking regularly can reduce stress and keep people active.')+'<h2>Answer B</h2>'+speech('Exercise is important and people can go walking and they can go to the gym and they can play football and they can swim and they can run and… yeah, there are lots of different things.')+choices('development','Which speaker develops an idea?',['A','B','Not sure'])+reveal('meaning','Compare the answers','<p><strong>A</strong> develops a point with an example. B lists more activities.</p><p>Answer B contains more things. Answer A contains more meaning.</p>')+'<p class="principle">Don’t search for more things to say. Build the idea you already have.</p>');
function topicIndex(){const i=picked('topic');return i!==undefined&&topics[i]?i:0;}
const practiceQuestion=()=>question(topics[topicIndex()][1]);
const practiceTool=()=>{const i=picked('practice-tool');return models[i]?`<p class="thinking-path">Your direction: ${models[i].label}</p>`:'<p>Choose a direction in your head, or go Back to select one.</p>';};
const fallback='<p class="hint">Use your phone’s voice recorder. This page does not record. If you cannot record, speak aloud and ask a partner to listen, or think back to your answer.</p>';
add('record','Choose a question',()=>'<p>Pick one question for this round. You can try another after your second attempt.</p>'+select('topic','Topic',topics.map(t=>t[0]))+`<div id="practice-question">${practiceQuestion()}</div>`+choices('practice-tool','Choose a way to think.')+'<p>It is a direction, not a script. No single tool is required.</p>','Use this question');
add('record','Answer once',()=>practiceQuestion()+practiceTool()+'<ol class="practice-steps"><li>Read the question.</li><li>Choose a thinking tool.</li><li>Think for about <strong>10 seconds</strong>.</li><li>Record for about <strong>20–30 seconds</strong>.</li><li>Listen once.</li></ol>'+fallback+'<p class="hint">These are classroom practice timings, not IELTS answer-length rules. Use your phone clock; there is no timer gate.</p>','I’ve answered');
add('record','Listen once. Check three things.',()=>practiceQuestion()+['Did I answer the question?','Can I follow my idea?','Did I develop one idea — or just add more things?'].map((q,i)=>choices('check-'+topicIndex()+'-'+i,q,i===2?['I developed an idea','I mainly added more things','Not sure']:['Yes','Not yet','Not sure'])).join('')+'<p>If you have no recording, use your partner’s feedback or what you remember.</p>');
add('record','Record it again',()=>practiceQuestion()+'<p class="principle">Don’t try to fix everything. Make the idea clearer.</p><p>Keep one point. Explain why, give one example or show what follows.</p><p>Record the same question again for about 20–30 seconds. Then listen.</p>'+fallback,'I’ve answered again');
add('record','Take the clearer idea with you',()=>'<p>Which part of your second answer was easier to follow? Tell a partner.</p><button data-repeat>Try another question</button><p class="hint">Choose a different theme for another short round, or continue to the model discussion.</p>');
add('adapt','Listen to the next question',()=>'<p>Read this model interaction, or listen if your teacher plays it externally. Notice how the candidate changes direction.</p><p class="hint">Workshop model, not an official IELTS recording.</p>'+dialogue.map((t,i)=>`<section class="dialogue-turn"><h2>Examiner</h2><p>${esc(t.question)}</p><h2>Candidate</h2>${speech(t.answer)}</section>`).join(''));
add('adapt','What changes?',()=>select('dialogue-0','What thinking tool does the candidate use first?',labels)+select('dialogue-1','What happens after “Is that necessarily a bad thing?”',labels)+select('dialogue-2','What happens when the examiner asks about the future?',labels)+reveal('dialogue-movement','Reveal the movement','<p><strong>One conversation. Three thinking tools.</strong></p><ol class="movement"><li>WHY? → WHAT HAPPENS?</li><li>GOOD → BUT…</li><li>IF… → MAYBE…</li></ol><p>The last answer imagines a future situation. It also looks ahead in time: tools can work together.</p><p>You don’t need to stay inside one pattern. Listen to the next question and change direction when you need to.</p>')+help('Read the model again',dialogue.map(t=>'<p><strong>Examiner:</strong> '+esc(t.question)+'</p>'+speech(t.answer)).join('')));
const followups=['Do you think convenience is always a good thing?','Could this change the way our towns and cities look?','What about older people? Is the situation the same for them?'];
function followBody(){return state.follow?`<p class="eyebrow">Follow-up ${state.follow} of 3</p>${question(followups[state.follow-1])}<p>Answer aloud. Listen to the new question, rather than repeating your first answer.</p>${state.follow<3?'<button data-follow>Next follow-up</button>':'<button data-follow-reset>Try the follow-ups again</button>'}`:'<button data-follow>Reveal the first follow-up</button>';}
add('adapt','The examiner isn’t necessarily finished',()=>'<p>The examiner may ask you to explain, defend or qualify an idea, compare it, think about another group, imagine a consequence or move it into the future.</p><h2>Candidate</h2>'+speech('I think online shopping is popular mainly because it’s convenient. People who work long hours don’t necessarily have time to visit different shops, so buying things online can save quite a lot of time.')+`<div id="followups" aria-live="polite">${followBody()}</div>`+'<p class="principle">Listen to the examiner. Your next question may grow from what you just said.</p>');
add('adapt','Let two tools work together',()=>question('Should governments do more to encourage people to exercise?')+speech('I think they probably should, because inactivity can cause serious health problems. For example, people who spend most of the day sitting may not get enough exercise. If governments created more parks and walking areas, people might become more active.',['I think','because','For example','If','might'])+reveal('mixed-model','Trace the thinking','<p class="thinking-path">OPINION → WHY? → EXAMPLE → IF… → MAYBE…</p><p>The imagined change grows from the problem. It is not a list of unrelated points.</p>'));
add('adapt','Now combine two',()=>question('Should schools give students more opportunities to learn outdoors?')+choices('mixed-tools','Choose up to TWO tools, or choose in your head.',labels,true)+'<p id="mixed-limit" role="status"></p><p>Think briefly, then answer aloud. Make the second direction grow from your first point. You do not need more than two.</p>');
add('transfer','A reference, not a script',()=>'<p>Open this only if it helps. Choose language that serves your idea; there is nothing to memorise.</p>'+help('Useful language by thinking function',models.map((m,i)=>`<section class="reference-group"><h2>${m.label}</h2><ul>${reference[i].map(p=>`<li>${p}</li>`).join('')}</ul></section>`).join(''))+'<p>Next: a short tourism discussion. The thinking labels disappear. React to each question as it comes.</p><p>Take turns as examiner and candidate if you have a partner. The examiner chooses when to move to the next question.</p>','Try it on your own');
finalQuestions.forEach((q,i)=>add('transfer',`Tourism · question ${i+1}`,()=>question(q)+'<p>Listen or read. Think. Answer aloud.</p><p>React to this question in your own way.</p>',i===4?'Finish the discussion':'Next question'));
add('transfer','Add more meaning',()=>'<p>You don’t need five perfect answer structures.</p><p>You need ways to think when the examiner asks you something difficult.</p><p class="principle">Choose a direction.<br>Build one idea.<br>Make it easy to follow.</p><p>Don’t add more things. Add more meaning.</p>','Finish Day 4');
function render(){state.step=Number.isInteger(state.step)?Math.max(0,Math.min(screens.length-1,state.step)):0;const s=screens[state.step],stage=control.stageForScreen(state.step);releaseUI.update(stage);document.getElementById('progress-label').textContent=`Day 4 · Stage ${releaseConfig.stages.indexOf(stage)+1} of 6 · ${stage.label}`;document.getElementById('progress').value=releaseConfig.stages.indexOf(stage)+1;app.innerHTML=control.isOpen(stage.id)?`<p class="eyebrow">Day 4 · ${stage.label}</p><h1>${s.title}</h1>${s.body()}<nav class="nav" aria-label="Activity navigation">${state.step?'<button data-back>Back</button>':''}<button data-next class="primary">${s.next}</button></nav>`:releaseUI.locked(stage);save();}
function jump(n){const u=new URL(location.href);u.searchParams.delete('stage');history.replaceState(null,'',u.pathname+u.search+u.hash);state.step=n;render();document.getElementById('activity').focus();scrollTo(0,0);}
app.addEventListener('change',e=>{const t=e.target;if(!t.matches('input[name],select[name]'))return;let values=t.tagName==='SELECT'?(t.value===''?[]:[Number(t.value)]):Array.from(app.querySelectorAll(`input[name="${t.name}"]:checked`),x=>Number(x.value));if(t.name==='mixed-tools'&&values.length>2){t.checked=false;values=values.filter(n=>n!==Number(t.value));document.getElementById('mixed-limit').textContent='Two is enough. Uncheck one if you want a different direction.';}state.answers[t.name]=values;save();if(t.name==='topic')document.getElementById('practice-question').innerHTML=practiceQuestion();});
app.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-next')){if(state.step===screens.length-1){control.complete('transfer');app.innerHTML='<h1>Keep thinking aloud</h1><p>Choose a direction. Build one idea. Make it easy to follow.</p><button data-review>Review Day 4</button>';return;}const stage=control.stageForScreen(state.step);if(control.stageForScreen(state.step+1).id!==stage.id)control.complete(stage.id);jump(state.step+1);}if(b.hasAttribute('data-back'))jump(state.step-1);if(b.hasAttribute('data-review'))jump(0);if(b.hasAttribute('data-repeat'))jump(13);if(b.dataset.show){const id=b.dataset.show;state.reveals[id]=!state.reveals[id];document.getElementById(id).hidden=!state.reveals[id];b.setAttribute('aria-expanded',String(state.reveals[id]));save();}if(b.hasAttribute('data-follow')||b.hasAttribute('data-follow-reset')){state.follow=b.hasAttribute('data-follow-reset')?0:Math.min(3,state.follow+1);document.getElementById('followups').innerHTML=followBody();document.querySelector('#followups button').focus();save();}});
releaseUI=installStudentRelease({control,app,progress:document.querySelector('.progress-wrap'),onJump:jump,onRefresh:render});
const requested=releaseConfig.stages.find(s=>s.id===new URLSearchParams(location.search).get('stage'));if(requested)state.step=requested.firstScreen;
render();
