const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');
const base=process.env.STUDENT_URL||'http://localhost:8000/listening/day-2/';
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});let released=[];
 const session={code:'ABC234',workshop:'listening-day-2',createdAt:Date.now(),expiresAt:Date.now()+28800000};
 const contexts=[];
 async function client(){const context=await browser.newContext();contexts.push(context);await context.route('**/release-config.js',async route=>{const response=await route.fetch();await route.fulfill({response,body:(await response.text()).replace('serviceReady=false','serviceReady=true')});});await context.routeWebSocket('**/v1/classes/**',socket=>{socket.close();});await context.route('**/v1/classes**',async route=>{const request=route.request();let status=200,data={...session,released};if(request.method()==='POST'&&request.url().includes('/release')){assert.equal(request.headers().authorization,'Bearer test-teacher');const body=request.postDataJSON();released=body.all?['l21','l22','l23','l24','l25','l26','l27','l28']:[...new Set([...released,body.activity])];data={...session,released};}else if(request.method()==='POST')data={...data,teacherToken:'test-teacher'};await route.fulfill({status,json:data});});const page=await context.newPage();page.on('pageerror',e=>{throw e;});return page;}
 const teacher=await client(),a=await client(),b=await client();await teacher.goto(base+'teacher-control/');await teacher.locator('#create-class').click();await teacher.locator('#classroom-code').filter({hasText:'ABC234'}).waitFor();
 for(const page of [a,b]){await page.goto(base);await page.locator('#class-code').fill('ABC234');await page.locator('#class-connect-form button').click();await page.getByText('Connected ✓',{exact:true}).waitFor();await page.locator('[name="l21-1"][value="B"]').check();await page.locator('[data-activity="l21"]').evaluate(f=>f.requestSubmit());assert.equal(await page.locator('#l21 .feedback').allTextContents().then(x=>x.join('')),'');assert.equal(await page.locator('#author-note').isVisible(),false);}
 await teacher.locator('[data-release="l21"]').click();for(const page of[a,b]){await page.locator('[data-answer-check="l21"]').waitFor({timeout:12000});assert(await page.locator('[name="l21-1"][value="B"]').isChecked());assert(!await page.locator('[data-answer-check="l22"]').isVisible());}
 const keys={l21:'BCCCBACBACB',l22:'213',l23:'654',l24:'CABC',l25:'EDCBAG',l26:'EBCIDF'};
 await teacher.locator('#release-all').click();await a.locator('[data-answer-check="l26"]').waitFor({timeout:12000});
 for(const[id,key]of Object.entries(keys)){const fields=a.locator(`#${id} fieldset`);for(let i=0;i<key.length;i++){const field=fields.nth(i);if(await field.locator('select').count())await field.locator('select').selectOption(key[i]);else await field.locator(`input[value="${key[i]}"]`).check();}await a.locator(`[data-answer-check="${id}"]`).click();assert((await a.locator(`#${id} .result`).innerText()).startsWith(`${key.length} / ${key.length}`));}
 assert(await a.locator('#author-note').isVisible());await a.locator('#author-note summary').click();assert((await a.locator('#author-note').innerText()).includes('Abdulrazak Gurnah'));
 await a.context().setOffline(true);await a.locator('[name="l27-4"]').fill('offline response');await a.context().setOffline(false);await a.reload();await a.locator('[data-answer-check="l26"]').waitFor({timeout:12000});assert.equal(await a.locator('[name="l27-4"]').inputValue(),'offline response');assert((await a.locator('#l26 .result').innerText()).startsWith('6 / 6'));await b.reload();await b.locator('[data-answer-check="l26"]').waitFor({timeout:12000});assert(await b.locator('[name="l21-1"][value="B"]').isChecked());
 await a.locator('[name="l21-1"][value="A"]').check();assert.equal(await a.locator('#l21 .result').innerText(),'');await a.locator('[data-answer-check="l21"]').click();assert((await a.locator('#l21 .result').innerText()).startsWith('10 / 11'));
 assert.equal(await a.locator('#l27 [data-answer-check],#l28 [data-answer-check]').count(),2);
 for(const width of[360,390,430,1280]){await a.setViewportSize({width,height:900});await a.locator('#l26').scrollIntoViewIfNeeded();await a.locator('#l26 img').evaluate(img=>img.decode());assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await a.locator('.map-figure img').evaluateAll(imgs=>Promise.all(imgs.map(img=>{img.loading='eager';return img.decode();})));const images=await a.locator('.map-figure img').evaluateAll(imgs=>imgs.map(img=>({src:img.getAttribute('src'),w:img.width,h:img.height,nw:img.naturalWidth,nh:img.naturalHeight})));assert.equal(images.length,8);for(const img of images){assert(img.nw>0);assert(Math.abs(img.w/img.h-img.nw/img.nh)<.03);}await a.screenshot({path:`/tmp/day2-campus-${width}.png`});await a.locator('#l25').scrollIntoViewIfNeeded();await a.screenshot({path:`/tmp/day2-market-${width}.png`});}
 // Stock local configuration: no active backend claim, no working release bypass.
 const stock=await browser.newContext();const p=await stock.newPage();await p.goto(base);const liveReady=await p.evaluate(async()=>{const c=await import('./release-config.js');return c.serviceReady;});assert.equal(await p.locator('#class-connect-form button').isDisabled(),!liveReady);assert.equal(await p.locator('[data-answer-check]:visible').count(),0);assert.equal(await p.locator('input:checked').count(),0);await p.goto(base+'teacher-control/');assert.equal(await p.locator('#create-class').isDisabled(),!liveReady);
 await browser.close();console.log('PASS: 3 isolated contexts with simulated service; all six keys, wrong answer, release isolation, pending marking, response/checked refresh, offline edits, eight original maps, 360/390/430/1280 layouts, stock activation guard. Not a live backend acceptance test.');
})().catch(e=>{console.error(e);process.exit(1)});
