const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true}),ctx=await browser.newContext();await ctx.route('**/shared/classroom/config.js',r=>r.fulfill({contentType:'application/javascript',body:"export const serviceURL='http://127.0.0.1:8788';"}));await ctx.route('**/release-config.js',async r=>{const s=await r.fetch();await r.fulfill({response:s,body:(await s.text()).replace('serviceReady=false','serviceReady=true')})});const p=await ctx.newPage();await p.goto('http://localhost:8000/listening/day-2/');await p.evaluate(()=>localStorage.setItem('ielts-listening-day-2-v1',JSON.stringify({responses:{'l28-1':'A','l27-4':'online'},checked:{l28:true},contentVersions:{l29:'final-six'}})));await p.reload();assert.equal(await p.locator('#l28 input:checked').count(),0);assert.equal(await p.locator('[name="l27-4"]').inputValue(),'online');assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('ielts-listening-day-2-v1')).archivedResponses.classificationOldOrder.responses['l28-1']),'A');
const response=await p.request.post('http://127.0.0.1:8788/v1/classes',{data:{workshop:'listening-day-2'}}),s=await response.json();assert(response.ok());await p.locator('#class-code').fill(s.code);await p.locator('#class-connect-form button').click();await p.getByText('Connected ✓',{exact:true}).waitFor();
for(const[i,v]of [...'CAB'].entries())await p.locator(`[name="l27-1-${i}"]`).selectOption(v);await p.locator('[name="l27-2"][value="B"]').check();await p.locator('[name="l27-3"]').fill('  PAY   course FEE  ');await p.locator('[name="l27-4"]').fill(' ONLINE ');for(const[i,v]of [...'2134'].entries())await p.locator(`[name="l27-5-${i}"]`).fill(v);
for(const[i,v]of [...'BACBCAACBBCA'].entries())await p.locator(`[name="l28-${i+1}"][value="${v}"]`).check();for(const id of['l27','l28']){await p.locator(`[data-activity="${id}"]`).evaluate(f=>f.requestSubmit());assert.equal(await p.locator(`#${id} .result`).innerText(),'');}assert.equal(await p.locator('#l28 .learning-layer').count(),0);
async function release(id){const r=await p.request.post(`http://127.0.0.1:8788/v1/classes/${s.code}/release?workshop=listening-day-2`,{headers:{Authorization:'Bearer '+s.teacherToken},data:{activity:id}});assert(r.ok());await p.locator(`[data-answer-check="${id}"]`).waitFor();}
await release('l27');assert(!await p.locator('[data-answer-check="l28"]').isVisible());await p.locator('[data-answer-check="l27"]').click();assert((await p.locator('#l27 .result').innerText()).startsWith('5 / 5'));await release('l28');await p.locator('[data-answer-check="l28"]').click();assert((await p.locator('#l28 .result').innerText()).startsWith('12 / 12'));assert.equal(await p.locator('#l28 .feedback.correct').count(),12);assert((await p.locator('#l28 .learning-layer').innerText()).includes('must not'));await p.reload();await p.locator('#l28 .learning-layer').waitFor();assert((await p.locator('#l27 .result').innerText()).startsWith('5 / 5'));assert.equal(await p.locator('#l28 input:checked').count(),12);
const permutations=a=>a.length?a.flatMap((x,i)=>permutations(a.filter((_,j)=>j!==i)).map(rest=>[x,...rest])):[[]];for(const [q,key]of[[1,[...'CAB']],[5,[...'2134']]]){for(const perm of permutations(key)){for(const[i,v]of perm.entries()){const input=p.locator(`[name="l27-${q}-${i}"]`);q===1?await input.selectOption(v):await input.fill(v);}await p.locator('[data-answer-check="l27"]').click();assert((await p.locator('#l27 .result').innerText()).startsWith(`${perm.join('')===key.join('')?5:4} / 5`));}for(const[i,v]of key.entries()){const input=p.locator(`[name="l27-${q}-${i}"]`);q===1?await input.selectOption(v):await input.fill(v);}}
for(const[q,wrong]of[[3,'pay fee'],[4,'offline']]){await p.locator(`[name="l27-${q}"]`).fill(wrong);await p.locator('[data-answer-check="l27"]').click();assert((await p.locator('#l27 .result').innerText()).startsWith('4 / 5'));await p.locator(`[name="l27-${q}"]`).fill(q===3?'pay course fee':'online');}
await p.addStyleTag({content:'html{scroll-behavior:auto!important}'});for(const width of[360,390,430,1280]){await p.setViewportSize({width,height:900});await p.locator('#l28').evaluate(e=>e.scrollIntoView({behavior:'instant'}));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.screenshot({path:`/tmp/classification-${width}.png`});}assert(fs.readFileSync('listening/day-2/source/transcripts/audio-2.8.txt').equals(fs.readFileSync('/Users/orlandorobson/Downloads/IELTS_listening_2.8_eng.txt')));await browser.close();console.log('PASS: 2.7 all order permutations, exact text boundaries and 5 marks; 2.8 12 marks, state archive, transcript bytes, release guards, refresh, four widths.');})().catch(e=>{console.error(e);process.exit(1)});
