const{chromium}=require('playwright');const assert=require('node:assert/strict');
const base='http://localhost:8000/listening/day-2/',api='http://127.0.0.1:8788';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
async function client(width=390){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'});await context.route('**/shared/classroom/config.js',route=>route.fulfill({contentType:'application/javascript',body:`export const serviceURL='${api}';`}));await context.route('**/release-config.js',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text()).replace('serviceReady=false','serviceReady=true')});});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});return page;}
const t=await client(1280),a=await client(),b=await client();await t.goto(base+'teacher-control/');await t.locator('#create-class').click();await t.locator('#teacher-session').waitFor();const code=(await t.locator('#classroom-code').innerText()).trim();assert.match(code,/^[A-HJ-NP-Z2-9]{6}$/);
for(const p of[a,b]){await p.locator('#class-code').fill(code);await p.locator('#class-connect-form button').click();await p.getByText('Connected ✓',{exact:true}).waitFor();await p.locator('[name="l29-1"][value="B"]').check();await p.locator('[name="l210-19–20"][value="C"]').check();await p.locator('[name="l210-19–20"][value="A"]').check();assert(await p.locator('[name="l210-19–20"][value="B"]').isDisabled());await p.locator('[data-activity="l210"]').evaluate(f=>f.requestSubmit());await p.locator('[data-activity="l29"]').evaluate(f=>f.requestSubmit());assert.equal(await p.locator('.learning-layer').count(),0);assert.equal(await p.locator('#l29 .result,#l210 .result').allTextContents().then(x=>x.join('')),'');await p.reload();assert(await p.locator('[name="l29-1"][value="B"]').isChecked());assert(await p.locator('[name="l210-19–20"][value="C"]').isChecked());await p.getByText('Connected ✓',{exact:true}).waitFor();}
await t.locator('[data-release="l29"]').click();for(const p of[a,b]){await p.locator('[data-answer-check="l29"]').waitFor();assert(!await p.locator('[data-answer-check="l210"]').isVisible());assert(await p.locator('[name="l29-1"][value="B"]').isChecked());}
// One client misses a release while offline, edits, then catches up via HTTP+push.
await a.context().setOffline(true);await a.locator('[name="l27-4"]').fill('My offline answer');await t.locator('[data-release="l210"]').click();await b.locator('[data-answer-check="l210"]').waitFor();await a.context().setOffline(false);await a.locator('[data-answer-check="l210"]').waitFor();assert.equal(await a.locator('[name="l27-4"]').inputValue(),'My offline answer');
for(const [i,v]of [...'BACABA'].entries())await a.locator(`[name="l29-${i+1}"][value="${v}"]`).check();await a.locator('[data-answer-check="l29"]').click();assert((await a.locator('#l29 .result').innerText()).startsWith('6 / 6'));assert.equal(await a.locator('#l29 .learning-layer').count(),1);await a.locator('#l29 .learning-layer summary').click();await a.locator('[name="reflection-l29"][value="1"]').check();
for(const [i,v]of [...'BBABCBAA'].entries())await a.locator(`[name="l210-${11+i}"][value="${v}"]`).check();await a.locator('[data-answer-check="l210"]').click();assert((await a.locator('#l210 .result').innerText()).startsWith('10 / 10'));await a.reload();await a.locator('#l210 .learning-layer').waitFor();assert(await a.locator('[name="reflection-l29"][value="1"]').isChecked());
// Editing hides learning and stale score; partial credit, maximum two selections.
await a.locator('[name="l210-19–20"][value="C"]').uncheck();assert.equal(await a.locator('#l210 .learning-layer').count(),0);await a.locator('[name="l210-19–20"][value="E"]').check();await a.locator('[data-answer-check="l210"]').click();assert((await a.locator('#l210 .result').innerText()).startsWith('9 / 10'));await a.locator('[name="l210-19–20"][value="A"]').uncheck();await a.locator('[name="l210-19–20"][value="B"]').check();await a.locator('[data-answer-check="l210"]').click();assert((await a.locator('#l210 .result').innerText()).startsWith('8 / 10'));
await t.locator('#release-all').click();for(const p of[a,b]){await p.locator('[data-answer-check="l21"]').waitFor();assert.equal(await p.locator('[data-answer-check]:visible').count(),10);assert.equal(await p.locator('#l27 [data-answer-check],#l28 [data-answer-check]').count(),2);}
const denied=await a.request.post(`${api}/v1/classes/${code}/release?workshop=listening-day-2`,{headers:{Authorization:'Bearer '+code},data:{all:true}});assert.equal(denied.status(),403);
const wrong=await a.request.get(`${api}/v1/classes/${code}?workshop=listening-day-1`);assert.equal(wrong.status(),409);
const publicState=await(await a.request.get(`${api}/v1/classes/${code}?workshop=listening-day-2`)).json();assert.deepEqual(Object.keys(publicState).sort(),['code','createdAt','expiresAt','released','workshop']);
for(const width of[360,390,430,1280]){await a.setViewportSize({width,height:900});for(const id of['l29','l210']){await a.locator('#'+id).evaluate(el=>el.scrollIntoView({block:'start',behavior:'instant'}));assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await a.screenshot({path:`/tmp/day2-final-${id}-${width}.png`});if(id==='l210')await a.locator('#l210 form fieldset').last().screenshot({path:`/tmp/petra-two-${width}.png`});const labels=await a.locator(`#${id} .option`).evaluateAll(es=>es.map(e=>e.getBoundingClientRect().height));assert(labels.every(h=>h>=44));}await t.setViewportSize({width,height:900});assert(await t.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
assert.equal(await a.locator('#l210 fieldset').count(),9);assert.equal(await a.locator('#l29 form fieldset').count(),6);assert.equal(await a.locator('#l29 input[type=checkbox],#l29 select').count(),0);
assert(!/[\u0600-\u06ff]/.test(await a.locator('#l210 form').innerText()));assert.deepEqual(errors,[]);
console.log('PASS: real local Worker + 3 isolated browser contexts; teacher/student separation, selective release/all, offline catch-up, refresh, two-answer cap/0/1/2 marks, exact 6/10 totals, private writes, four responsive widths. No deployed/physical-device claim.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
