const{chromium}=require('playwright'),assert=require('node:assert/strict');
const base=process.env.STUDENT_URL||'https://orlandorobson.github.io/ielts-workshops/listening/day-2/',api='https://ielts-classroom-release.ielts-classroom-release.workers.dev';
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];async function page(){const ctx=await browser.newContext();if(process.env.PRE_ACTIVATION==='1')await ctx.route('**/release-config.js',async r=>{const response=await r.fetch();await r.fulfill({response,body:(await response.text()).replace('serviceReady=false','serviceReady=true')});});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));return p;}const t=await page(),a=await page(),b=await page();
assert.equal((await t.goto(base+'teacher-control/')).status(),200);await t.locator('#create-class').click();await t.locator('#teacher-session').waitFor();const code=(await t.locator('#classroom-code').innerText()).trim();assert.match(code,/^[A-HJ-NP-Z2-9]{6}$/);
for(const p of[a,b]){assert.equal((await p.goto(base)).status(),200);assert.equal(await p.locator('section.activity').count(),10);assert.equal(await p.locator('#l28 form fieldset').count(),12);assert.equal(await p.locator('#l29 form fieldset').count(),6);assert.equal(await p.locator('#l210 form fieldset').count(),9);await p.locator('#class-code').fill(code);await p.locator('#class-connect-form button').click();await p.getByText('Connected ✓',{exact:true}).waitFor();await p.locator('[name="l29-1"][value="B"]').check();await p.locator('[data-activity="l29"]').evaluate(f=>f.requestSubmit());assert.equal(await p.locator('#l29 .result').innerText(),'');assert(!await p.locator('[data-answer-check="l29"]').isVisible());await p.reload();assert(await p.locator('[name="l29-1"][value="B"]').isChecked());await p.getByText('Connected ✓',{exact:true}).waitFor();}
await t.locator('[data-release="l29"]').click();for(const p of[a,b]){await p.locator('[data-answer-check="l29"]').waitFor();assert(!await p.locator('[data-answer-check="l28"]').isVisible());}for(const[i,v]of[...'BACABA'].entries())await a.locator(`[name="l29-${i+1}"][value="${v}"]`).check();await a.locator('[data-answer-check="l29"]').click();assert((await a.locator('#l29 .result').innerText()).startsWith('6 / 6'));await a.reload();await a.locator('#l29 .learning-layer').waitFor();assert((await a.locator('#l29 .result').innerText()).startsWith('6 / 6'));
await a.context().setOffline(true);await a.locator('[name="l27-4"]').fill('online');await t.locator('[data-release="l28"]').click();await b.locator('[data-answer-check="l28"]').waitFor();await a.context().setOffline(false);await a.locator('[data-answer-check="l28"]').waitFor();assert.equal(await a.locator('[name="l27-4"]').inputValue(),'online');
await t.locator('#release-all').click();for(const p of[a,b])await p.waitForFunction(()=>document.querySelectorAll('[data-answer-check]:not([hidden])').length===10);assert.equal(await t.locator('#release-activities button:disabled').count(),10);
assert.equal((await a.request.post(`${api}/v1/classes/${code}/release?workshop=listening-day-2`,{headers:{Authorization:'Bearer '+code},data:{all:true}})).status(),403);const state=await(await a.request.get(`${api}/v1/classes/${code}?workshop=listening-day-2`)).json();assert.equal(state.expiresAt-state.createdAt,28800000);assert.deepEqual(Object.keys(state).sort(),['code','createdAt','expiresAt','released','workshop']);assert.equal((await a.request.get(`${api}/v1/classes/ZZZZZZ?workshop=listening-day-2`)).status(),404);
for(const width of[360,390,430,1280]){for(const p of[a,t]){await p.setViewportSize({width,height:900});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await a.locator('#workshop-menu').evaluate(e=>e.open=true);await a.locator('#navigation a[href="#l210"]').click();assert.equal(new URL(a.url()).hash,'#l210');await a.screenshot({path:`/tmp/published-day2-${width}.png`});}
// Day 1 on the same real frontend origin, with independent teacher/student stores.
const d1=new URL('../day-1/',base).href,dt=await page(),ds=await page();assert.equal((await dt.goto(d1+'teacher-control/')).status(),200);await dt.locator('#create-class').click();await dt.locator('#teacher-session').waitFor();const dc=(await dt.locator('#classroom-code').innerText()).trim();assert.equal((await ds.goto(d1)).status(),200);await ds.locator('#class-code').fill(dc);await ds.locator('#class-connect-form button').click();await ds.getByText('Connected ✓',{exact:true}).waitFor();await ds.locator('#l14-0').fill('two');await dt.locator('[data-release="l14"]').click();await ds.locator('[data-answer-check="l14"]').waitFor();assert.equal(await ds.locator('#l14-0').inputValue(),'two');await ds.locator('[data-answer-check="l14"]').click();await ds.reload();await ds.getByText('Connected ✓',{exact:true}).waitFor();assert.equal(await ds.locator('#l14-0').inputValue(),'two');assert.deepEqual(errors,[]);await browser.close();console.log('PASS real deployed backend + '+base+': HTTP200 student/teacher, 3 independent Day2 clients, session/create/read, selective releases/all, 403 writes, 404 invalid, eight-hour metadata, offline/reload feedback, 4 widths; independent Day1 create/release/persistence. Expiry cleanup tested locally, no physical-phone claim.');})().catch(e=>{console.error(e);process.exit(1)});
