import {lesson as C} from '../content.js';
import {continuationTeacher} from '../continuation-teacher.js';
import {headingOrders} from '../answer-order.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles=['Flexible Working','Urban Trees','How an LLM Produces a Response','Curitiba','Mohammed from Sohar','The Transformation of Bedouin Life in the Modern Arabian Peninsula','You Are What You Eat—Or Are You?'];
const ranges=['2–3','4–5','6–8','9–11','12–13','14–22','37–40'];
const names=['flexible','trees','llm','curitiba','mohammed','bedouin','food'];
const sourceStarts=C.source.map((s,i)=>s.startsWith('Activity ')?i:-1).filter(i=>i>=0);
document.getElementById('guide').innerHTML=titles.map((title,i)=>{const chunk=C.source.slice(sourceStarts[i],sourceStarts[i+1]||C.source.length);const notes=chunk.filter(t=>t.startsWith('TEACHER / IMPLEMENTATION NOTE:'));const key=C.keys[names[i]];return (i===6?continuationTeacher():'')+`<section><p class="eyebrow">Activity ${i===6?9:i+1} · Steps ${ranges[i]}</p><h2>${esc(title)}</h2><p>${esc(chunk.find(s=>s.startsWith('Reading aim:'))||'')}</p><p><strong>${key?key.map((v,j)=>`${key.length>1?'Paragraph '+String.fromCharCode(65+j)+': ':''}${String.fromCharCode(65+headingOrders[names[i]].indexOf(v))} — ${esc(C.headings[names[i]][v])}`).join(' · '):'Same topic, different functions: A explains why online communication was easier; B traces change and qualifies it.'}</strong></p>${notes.map(t=>`<p>${esc(t)}</p>`).join('')}${(C.feedback[names[i]]||[]).map((t,j)=>`<p>${key.length>1?String.fromCharCode(65+j)+'. ':''}${esc(t)}</p>`).join('')}</section>`;}).join('')+`<section><h2>Source design principles and final progression notes</h2>${[...C.source.slice(9,16),...C.source.slice(C.source.indexOf('Three reading tools earned by the Bedouin text'))].filter(Boolean).map(t=>`<p>${esc(t)}</p>`).join('')}</section>`;
