import {activities} from './content.js';
import {transcripts} from './transcripts.js';
import {workshop,stages,serviceReady} from './release-config.js';
import {ClassroomConnection,mountStudentConnection} from '../../shared/classroom/client.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='ielts-listening-day-4-v1';let state={responses:{},checked:{}};
try{const v=JSON.parse(localStorage.getItem(key));if(v?.responses&&v?.checked)state=v;}catch{}
if(state.speakerSchema!==2){const old=[1,2,3,4].map(i=>state.responses['l44-'+i]);state.archived44={responses:old,checked:!!state.checked.l44};for(const [i,letter] of ['A','B','C','D'].entries()){const matches=old.map((v,j)=>v===letter?String(j+1):null).filter(Boolean);state.responses['l44-'+(i+1)]=matches.length===1?matches[0]:'';}state.checked.l44=false;state.speakerSchema=2;}
for(const responseKey of Object.keys(state.responses))if(/^l45-heard-/.test(responseKey))delete state.responses[responseKey];
function save(){try{localStorage.setItem(key,JSON.stringify(state));}catch{document.querySelector('#storage-note').textContent='Saving is unavailable in this browser. Keep this page open to retain your responses.';}}
const connection=new ClassroomConnection(workshop,stages),byId=id=>activities.find(a=>a.id===id),name=(a,q,i)=>`${a.id}-${q.number??i+1}`;
function sourceReady(a){return (a.requiresAll||[a.requires].filter(Boolean)).every(id=>connection.isOpen(id)&&!!state.checked[id]&&sourceReady(byId(id)));}
function canCheck(a){return !a.independent&&connection.isOpen(a.id)&&sourceReady(a);}
function field(a,q,i){const n=name(a,q,i);if(q.type==='text')return `<label class="visually-hidden" for="${n}">${esc(q.label)}</label><input id="${n}" name="${n}" type="text" autocomplete="off" spellcheck="false">`;if(q.type==='order'||q.type==='speaker')return `<label class="visually-hidden" for="${n}">${q.type==='speaker'?'Speaker':'Position'} for ${esc(q.label)}</label><select id="${n}" name="${n}"><option value="">${q.type==='speaker'?'Choose a speaker':'Choose a position'}</option>${q.options.map(o=>`<option value="${o.value}">${o.text}</option>`).join('')}</select>`;return `<div class="options ${q.sharedOptions?'letter-options':''}">${q.options.map(o=>`<label class="option"><input type="${q.type==='reflection'?'checkbox':'radio'}" name="${n}" value="${o.value}"><span>${esc(o.value)}${q.sharedOptions?'':'. '+esc(o.text)}</span></label>`).join('')}</div>`;}
function question(a,q,i){const n=name(a,q,i);return `${q.group?`<h3>${esc(q.group)}</h3>`:''}${q.before?`<p>${esc(q.before)}</p>`:''}${q.sharedOptions&&q.number===36?`<div class="answer-bank">${q.options.map(o=>`<p><b>${o.value}</b> ${esc(o.text)}</p>`).join('')}</div>`:''}<fieldset data-question="${n}"><legend>${q.number??i+1}. ${esc(q.label)}</legend>${q.extract?`<div data-extract="${i}"></div>`:''}${q.refs?`<div data-evidence="${i}"></div>`:''}${field(a,q,i)}<p class="feedback" data-feedback="${n}"></p>${q.say?`<div data-say="${i}"></div>`:''}</fieldset>${q.after?`<p>${esc(q.after)}</p>`:''}`;}
function chart(a){return `<div class="shape-chart">${a.chart.map((box,i)=>`<div class="shape-node"><span class="muted">${i+1}</span><p>${esc(box.label)}</p>${box.numbers.map(n=>{const q=a.questions.find(q=>q.number===n);return `<label for="${a.id}-${n}">${esc(q.label)}</label>${field(a,q,n-1)}<p class="feedback" data-feedback="${a.id}-${n}"></p>`}).join('')}</div>`).join('')}</div>`;}
const circled=n=>String.fromCodePoint(0x2460+n-1);
document.querySelector('#navigation').innerHTML=activities.map(a=>`<a href="#${a.id}">${esc(a.title)}</a>`).join('');
document.querySelector('#activities').innerHTML=activities.map((a,i)=>`<section class="activity" id="${a.id}"><p class="eyebrow">${esc(a.eyebrow)}</p><h2>${esc(a.title)}</h2><p>${esc(a.instruction)}</p>${a.requires||a.requiresAll?'<p data-source-wait class="muted">Complete and check the earlier listening before reviewing its extracts. You can keep navigating and working.</p>':''}${a.transcript?`<div data-transcript><div class="transcript-reading">${transcripts[a.transcript].paragraphs.map((_,j)=>paragraphHTML(a.transcript,j,a.id)).join('')}</div></div>`:''}${a.comparison?'<div data-comparison></div>':''}<form data-activity="${a.id}" ${a.opinion?'data-opinion':''}>${a.chart?chart(a):a.questions.map((q,j)=>question(a,q,j)).join('')}${a.prediction?'<p>Now follow the next recording with your teacher. Keep this prediction lightly: the speaker can take another direction. Tell your partner what you actually hear.</p>':''}${!a.independent?`<p class="muted" data-wait>Your teacher will release ${a.pending?'review':'checking'}. Keep working and change your answers freely.</p><button type="submit" data-answer-check="${a.id}" hidden disabled>${a.pending?'Review with your teacher':'Check & reflect'}</button>`:''}<p class="result" role="status"></p><div class="review-layer" hidden></div></form>${a.journey?'<div data-journey></div>':''}${a.image?`<figure><img src="assets/${a.image}" loading="lazy" alt="${a.id==='l47'?'Petroleum industry facilities.':'Illustration of a patient visiting a robot doctor.'}"></figure>`:''}<a class="next" href="#${activities[i+1]?.id||'finish'}">Continue →</a></section>`).join('');
const normal=x=>String(x??'').trim().replace(/\s+/g,' ').toLowerCase();
function clear(a){const f=document.querySelector(`[data-activity="${a.id}"]`);f.querySelectorAll('.feedback').forEach(el=>{el.textContent='';el.classList.remove('correct');});f.querySelector('.result').textContent='';const layer=f.querySelector('.review-layer');layer.replaceChildren();layer.hidden=true;f.querySelectorAll('[data-model]').forEach(el=>el.remove());}
function review(a){if(!canCheck(a))return;const f=document.querySelector(`[data-activity="${a.id}"]`);let score=0,total=0;a.questions.forEach((q,i)=>{if(q.answer==null)return;const n=name(a,q,i),expected=Array.isArray(q.answer)?q.answer:[q.answer],value=normal(state.responses[n]),correct=expected.some(v=>normal(v)===value)&&(!q.limit||value.split(' ').length<=q.limit);total++;score+=+correct;const p=f.querySelector(`[data-feedback="${n}"]`);p.textContent=correct?'Correct.':`Review this one. ${q.options?q.answer+' — '+q.options.find(o=>o.value===q.answer).text:expected[0]}`;p.classList.toggle('correct',correct);});f.querySelector('.result').textContent=a.pending?a.pending:`${score} / ${total} · Now notice how the speaker helped you follow.`;const layer=f.querySelector('.review-layer');layer.innerHTML=(a.shape?`<ol class="thinking-path">${a.shape.map(x=>`<li>${esc(x)}</li>`).join('')}</ol>`:'')+(a.phrases?`<p>${a.phrases.map(esc).join(' · ')}</p>`:'')+(a.review? a.review.map(x=>`<p>${esc(x)}</p>`).join(''):'');layer.hidden=!layer.innerHTML;state.checked[a.id]=true;save();refresh();}


function paragraphHTML(kind,index,prefix){const t=transcripts[kind],text=t.paragraphs[index],phrases=t.phrases.filter(p=>p.paragraph===index+1).map(p=>({...p,start:text.indexOf(p.text)})).sort((a,b)=>a.start-b.start);let output='',offset=0;for(const p of phrases){output+=esc(text.slice(offset,p.start))+`<strong id="${prefix}-phrase-${p.number}" data-highlight="${p.number}"><span class="phrase-number" aria-label="Phrase ${p.number}">${circled(p.number)} </span>${esc(p.text)}</strong>`;offset=p.start+p.text.length;}output+=esc(text.slice(offset));return `<p class="transcript-paragraph" data-paragraph="${index+1}"><span class="paragraph-number">Paragraph ${index+1}</span><span class="transcript-words">${output}</span></p>`;}
function renderAnalysis(a,section,ready){section.querySelectorAll('[data-evidence]').forEach(el=>{if(!ready){el.replaceChildren();return;}if(el.children.length)return;const q=a.questions[Number(el.dataset.evidence)],label=q.refs.length===1?'paragraph '+q.refs[0]:'paragraphs '+q.refs[0]+'–'+q.refs.at(-1);el.innerHTML=`<details class="evidence"><summary>Read ${label}</summary><div class="transcript-reading">${q.refs.map(i=>paragraphHTML(a.transcriptRef,i-1,`${a.id}-${el.dataset.evidence}`)).join('')}</div></details>`;});
const opinion=section.querySelector('[data-opinion]');if(opinion)opinion.hidden=false;
const comparison=section.querySelector('[data-comparison]');if(comparison)comparison.innerHTML=ready?`<div class="comparison"><div><h3>Petroleum</h3><p>“The difficulty, however”</p></div><div><h3>Concrete</h3><p>“Great, except now”</p></div><p class="shared-job">A problem or limitation is coming.</p></div><p>The petroleum speaker often announces the next area and balances benefits with limits. The concrete speaker often asks questions, reacts conversationally and corrects what a listener might imagine. Both help us follow the thinking.</p>`:'';
}
function syncSpeakers(){const fields=[...document.querySelectorAll('#l44 select')];for(const select of fields)for(const option of select.options)option.disabled=!!option.value&&fields.some(other=>other!==select&&other.value===option.value);}

function excerpt(q){const parts=q.extract.split(q.focus);return parts.map(esc).join(`<strong>${esc(q.focus)}</strong>`);}
function refresh(){for(const a of activities){const s=document.getElementById(a.id),f=s.querySelector('form'),ready=sourceReady(a),open=canCheck(a),button=s.querySelector('[data-answer-check]');if(button){button.hidden=!open;button.disabled=!open;s.querySelector('[data-wait]').hidden=open;if(!open)clear(a);}if(a.requires||a.requiresAll)s.querySelector('[data-source-wait]').hidden=ready;renderAnalysis(a,s,ready);s.querySelectorAll('[data-extract]').forEach(el=>{const q=a.questions[Number(el.dataset.extract)];el.innerHTML=ready?`<blockquote>${excerpt(q)}</blockquote>`:'';});s.querySelectorAll('[data-say]').forEach(el=>{const i=Number(el.dataset.say),q=a.questions[i],already=el.querySelector('[data-model]')?.getAttribute('aria-expanded')==='true';el.innerHTML=ready?`<p><b>Say it</b> · ${esc(q.say)}</p><p class="sentence-scaffold">${esc(q.stem)}</p><p class="muted">Ideas: ${esc(q.cue)}</p><p>Say the sentence aloud. No typing.</p>${open&&state.checked[a.id]?`<button class="secondary" type="button" data-model="${i}" aria-expanded="${already}" aria-controls="model-${a.id}-${i}">${already?'Hide & try again':'I’ve said it — show one way'}</button><p id="model-${a.id}-${i}" ${already?'':'hidden'}>${esc(q.model)}</p>`:''}`:'';});const journey=s.querySelector('[data-journey]');if(journey)journey.innerHTML=ready?`<ol class="thinking-path journey">${a.journey.map(([label,text])=>`<li><b>${esc(label)}</b><p>${esc(text)}</p></li>`).join('')}</ol>`:'';}}
for(const a of activities){const f=document.querySelector(`[data-activity="${a.id}"]`);for(const input of f.querySelectorAll('input,select')){const v=state.responses[input.name];if(input.type==='checkbox')input.checked=Array.isArray(v)&&v.includes(input.value);else if(input.type==='radio')input.checked=v===input.value;else input.value=v??'';}f.addEventListener('input',e=>{const input=e.target;if(!input.name)return;state.responses[input.name]=input.type==='checkbox'?[...f.querySelectorAll('input[type=checkbox]')].filter(el=>el.name===input.name&&el.checked).map(el=>el.value):input.value;state.checked[a.id]=false;clear(a);save();refresh();syncSpeakers();});f.addEventListener('submit',e=>{e.preventDefault();review(a);});f.addEventListener('click',e=>{const button=e.target.closest('[data-model]');if(!button||!canCheck(a)||!state.checked[a.id])return;const p=document.getElementById(button.getAttribute('aria-controls'));p.hidden=!p.hidden;button.setAttribute('aria-expanded',String(!p.hidden));button.textContent=p.hidden?'I’ve said it — show one way':'Hide & try again';});}
connection.subscribe(()=>{refresh();for(const a of activities)if(state.checked[a.id]&&canCheck(a))review(a);});
syncSpeakers();refresh();const panel=mountStudentConnection(connection,document.querySelector('#activities'));if(!serviceReady){panel.querySelectorAll('input,button').forEach(e=>e.disabled=true);panel.querySelector('#class-status').textContent='Local draft: Day 4 classroom activation is pending. You can keep working.';}
if(matchMedia('(max-width:850px)').matches)document.querySelector('#workshop-menu').open=false;document.querySelector('#navigation').addEventListener('click',e=>{if(e.target.closest('a')&&matchMedia('(max-width:850px)').matches)document.querySelector('#workshop-menu').open=false;});
