const KEY='ielts-personal-study-v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const observations=['Made me curious','Made a difficult idea understandable','Used examples well','Was easy to follow','Sounded genuinely interested','Used their voice effectively','Used visuals effectively','Made me think differently','Made me want to know more','I want to try something they did'];
const interests={all:'A little of everything',ai:'AI, technology & creativity',science:'Science & surprising ideas',ocean:'Oceans & environment',history:'History & the Islamic world',business:'Business, success & money',stories:'Stories & communication',speaker:'Become a stronger speaker',podcasts:'Podcasts for listening'};
const groups={history:['You’re Dead to Me','Travel, leaders and worlds worth discovering. Choose one episode from this BBC history-and-comedy collection.'],business:['Good Bad Billionaire','Five stories about business, wealth and influence. Choose a person you’re curious about; you don’t need to agree with the hosts.'],speaker:['Go further · Public Speaking 101','Optional TED-Ed lessons for a difficulty you recognise. You do not need these lessons for IELTS.']};
let items=[],state={items:{},notes:[],draft:''},filter='all',persistent=true;
function storageMessage(){ $('#storage-status').textContent=persistent?'Saved in this browser on this device. No account, uploads or scores. Clearing browser data removes these notes.':'This browser cannot save your notes right now. You can still explore and write here while the page stays open. Copy anything you want to keep before leaving.';}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));persistent=true;}catch{persistent=false;}storageMessage();}
function itemState(id){return state.items[id]??={observations:[],borrow:'',explored:false,again:false,dismissed:false};}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));if(s&&typeof s==='object'){
 for(const a of items){const v=s.items?.[a.id];if(v&&typeof v==='object')state.items[a.id]={observations:Array.isArray(v.observations)?v.observations.filter(x=>observations.includes(x)):[],borrow:typeof v.borrow==='string'?v.borrow.slice(0,1500):'',explored:v.explored===true,again:v.again===true,dismissed:v.dismissed===true};}
 state.notes=Array.isArray(s.notes)?s.notes.filter(n=>n&&typeof n.id==='string'&&typeof n.text==='string'&&typeof n.kind==='string').map(n=>({id:n.id,text:n.text.slice(0,3000),kind:n.kind.slice(0,80)})):[];
 state.draft=typeof s.draft==='string'?s.draft.slice(0,3000):'';
 }}catch{persistent=false;}save();}
function art(a){return a.image?`<img class="editorial-image" src="${a.image}" alt="${esc(a.alt)}" width="1536" height="1024" ${a.featured?'decoding="async"':'loading="lazy" decoding="async"'}>`:'';}
function related(a){return `<details class="related"><summary>More like this <span class="closed-arrow" aria-hidden="true">→</span><span class="open-arrow" aria-hidden="true">↓</span></summary><div class="related-list">${a.relatedIds.map(id=>items.find(x=>x.id===id)).filter(Boolean).slice(0,3).map(r=>`<a href="#item-${r.id}" data-return="${r.id}"><span class="metadata">${esc(r.who)}</span><strong>${esc(r.title)}</strong><small>${esc(r.themes||r.topics.map(t=>interests[t]).join(' · '))}</small></a>`).join('')}</div></details>`;}
function mediaLabel(a){if(a.url.includes('bbc.co.uk'))return 'Listen on BBC';if(a.url.includes('podcasts.apple'))return 'Listen on Apple Podcasts';if(a.url.includes('youtube'))return 'Watch on YouTube';if(a.who.includes('TED-Ed'))return 'Open TED-Ed';return 'Watch on TED';}
function reflection(a){const s=itemState(a.id);return `<details class="reflection"><summary>Notice or try something · optional</summary><div><fieldset><legend>What worked for you?</legend><div class="observations">${observations.map((o,i)=>`<label><input type="checkbox" data-observation="${i}" ${s.observations.includes(o)?'checked':''}>${o}</label>`).join('')}</div></fieldset><label for="borrow-${a.id}">What would you borrow?</label><textarea id="borrow-${a.id}" data-borrow rows="2" maxlength="1500">${esc(s.borrow)}</textarea><p class="small">If you like, try it with an idea of your own. You can adapt a speaking choice without copying an accent.</p>${a.follow?`<p>${a.follow}</p>`:''}<div class="personal-flags"><label><input type="checkbox" data-flag="explored" ${s.explored?'checked':''}>I’ve explored this</label><label><input type="checkbox" data-flag="again" ${s.again?'checked':''}>I’d like to hear them again</label></div><p class="small">Your choices and notes appear in My notebook.</p></div></details>`;}
function fallback(a){return `<details class="fallback"><summary>Link won’t open?</summary><div><p>The media opens on another website. If it is blocked, asks for payment or cannot play, choose something else—you can still use this page.</p>${a.alternate?`<p><a href="${a.alternate}" target="_blank" rel="noopener noreferrer">Try the producer’s Vimeo page (new tab)</a></p>`:''}<label for="link-${a.id}">Copy this link, or look for “${esc(a.title)}” by ${esc(a.who)} in your usual app.</label><input id="link-${a.id}" readonly value="${esc(a.url)}" aria-label="Link to ${esc(a.title)}"><button class="quiet-button" data-copy>Copy link</button><p class="copy-status" role="status"></p></div></details>`;}
function body(a){const s=itemState(a.id);return `<p class="metadata">${esc(a.who)}</p><p class="why">${esc(a.why)}</p>${a.themes?`<p class="themes">${esc(a.themes)}</p>`:''}<a class="media-link" href="${a.url}" target="_blank" rel="noopener noreferrer">${mediaLabel(a)} <span aria-hidden="true">↗</span><small>Opens in a new tab</small></a>${a.context?`<p class="context">${esc(a.context)} ${a.source?`<a href="${a.source}" target="_blank" rel="noopener noreferrer">Production credits (new tab)</a>`:''}</p>`:''}<p class="notice"><strong>Notice · if you like</strong>${esc(a.notice)}</p>${related(a)}${reflection(a)}<div class="actions"><button data-dismiss aria-pressed="${s.dismissed}">${s.dismissed?'Not for me · undo':'Not for me'}</button></div><div class="suggestion" role="status"></div>${fallback(a)}`;}
function card(a,featured=false){return `<article id="item-${a.id}" data-item="${a.id}" class="recommendation ${featured?'feature':a.image?'gateway-card':'browse-item'}">${art(a)}<div class="card-body">${a.diagnosis?`<p class="diagnosis">${esc(a.diagnosis)} →</p>`:''}<h3>${esc(a.title)}</h3>${body(a)}</div></article>`;}
function gateways(){return ['history','business'].map(id=>{const list=items.filter(a=>a.group===id);return `<section class="gateway-collection" aria-labelledby="${id}-title"><div class="section-heading"><h2 id="${id}-title">${groups[id][0]}</h2><p>${id==='history'?'Travel, cultures and lives across time.':'Familiar names. Unexpected stories.'}</p></div>${card(list[0])}<div class="episode-grid">${list.slice(1).map(a=>card(a)).join('')}</div></section>`;}).join('');}
function isGateway(a){return a.featured||a.group==='history'||a.group==='business';}
function browse(){const selected=items.filter(a=>!isGateway(a)&&(filter==='all'||a.topics.includes(filter)));const earlier=filter==='all'?[]:items.filter(a=>isGateway(a)&&a.topics.includes(filter));$('#results-label').textContent=filter==='all'?'Something else to catch your interest.':interests[filter];$('#recommendations').innerHTML=(earlier.length?`<div class="earlier-picks"><p class="small">From the collections above</p>${earlier.map(a=>`<a href="#item-${a.id}" data-return="${a.id}">${esc(a.title)}</a>`).join('')}</div>`:'')+selected.filter(a=>!a.group).map(a=>card(a)).join('')+(()=>{const list=selected.filter(a=>a.group==='speaker');return list.length?`<details class="collection" ${filter==='speaker'?'open':''}><summary>${groups.speaker[0]}</summary><div><p>${groups.speaker[1]}</p>${list.map(a=>card(a)).join('')}</div></details>`:''})();$('#interests').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.interest===filter)));}
function notebook(){
 $('#saved-notes').innerHTML=state.notes.map(n=>`<article class="saved-entry"><p class="metadata">${esc(n.kind)}</p><p>${esc(n.text)}</p><button class="quiet-button" data-delete="${esc(n.id)}">Remove note</button></article>`).join('');
 for(const [target,prop] of [['explored-list','explored'],['again-list','again'],['borrow-list','borrow']]){
 const list=items.filter(a=>prop==='borrow'?(itemState(a.id).borrow||itemState(a.id).observations.length):itemState(a.id)[prop]);
 $('#'+target).innerHTML=list.length?list.map(a=>`<div class="saved-reflection"><a href="#item-${a.id}" data-return="${a.id}">${esc(a.title)}</a>${prop==='borrow'?`<p>${esc(itemState(a.id).observations.join(' · '))}</p><p>${esc(itemState(a.id).borrow)}</p>`:''}</div>`).join(''):'<p class="small">Nothing here yet. Save something only if it matters to you.</p>';
 }
}
function goTo(id,remember=true){const a=items.find(x=>x.id===id);if(!a)return;
 if(remember){const source=document.activeElement?.closest('[data-item]')?.dataset.item;history.replaceState({personalStudy:{filter,y:scrollY,source}},'',location.href);history.pushState({personalStudy:{target:id}},'','#item-'+id);}
 if(!isGateway(a)&&!$('#item-'+id)){filter='all';browse();}
 const el=$('#item-'+id);let p=el;while(p){if(p.tagName==='DETAILS')p.open=true;p=p.parentElement;}
 el.scrollIntoView({block:'start'});const focus=el.querySelector('h3');focus.tabIndex=-1;focus.focus({preventScroll:true});}
window.addEventListener('popstate',e=>{const v=e.state?.personalStudy;if(v?.target){goTo(v.target,false);return;}if(v){filter=interests[v.filter]?v.filter:'all';browse();if(v.source)goTo(v.source,false);window.scrollTo({top:v.y||0,behavior:'instant'});}else if(location.hash.startsWith('#item-'))goTo(location.hash.slice(6),false);});
document.addEventListener('change',e=>{const el=e.target.closest('[data-item]');if(!el)return;const s=itemState(el.dataset.item);if(e.target.hasAttribute('data-observation')){const o=observations[Number(e.target.dataset.observation)];s.observations=e.target.checked?[...new Set([...s.observations,o])]:s.observations.filter(v=>v!==o);}else if(e.target.dataset.flag)s[e.target.dataset.flag]=e.target.checked;else return;save();notebook();});
document.addEventListener('input',e=>{if(e.target.hasAttribute('data-borrow')){itemState(e.target.closest('[data-item]').dataset.item).borrow=e.target.value;save();notebook();}if(e.target.id==='note-text'){state.draft=e.target.value;save();}});
document.addEventListener('click',async e=>{const b=e.target.closest('button,a');if(!b)return;
 if(b.dataset.interest){filter=b.dataset.interest;browse();}
 if(b.dataset.return){e.preventDefault();goTo(b.dataset.return);}
 if(b.hasAttribute('data-dismiss')){const el=b.closest('[data-item]'),a=items.find(x=>x.id===el.dataset.item),s=itemState(a.id);s.dismissed=!s.dismissed;save();b.setAttribute('aria-pressed',String(s.dismissed));b.textContent=s.dismissed?'Not for me · undo':'Not for me';const alternative=items.find(x=>x.id!==a.id&&!itemState(x.id).dismissed&&x.topics[0]!==a.topics[0]);el.querySelector('.suggestion').innerHTML=s.dismissed?(alternative?`A different direction: <a href="#item-${alternative.id}" data-return="${alternative.id}">${esc(alternative.title)}</a>. You can always come back.`:'Choose any other interest above. Nothing is hidden or locked.') : '';}
 if(b.hasAttribute('data-copy')){const el=b.closest('.fallback'),input=el.querySelector('input');try{await navigator.clipboard.writeText(input.value);el.querySelector('.copy-status').textContent='Link copied.';}catch{input.focus();input.select();el.querySelector('.copy-status').textContent='The link is selected. Use your device’s Copy command.';}}
 if(b.dataset.delete){state.notes=state.notes.filter(n=>n.id!==b.dataset.delete);save();notebook();$('#note-text').focus();$('#note-status').textContent='Note removed.';}
});
$('#note-form').addEventListener('submit',e=>{e.preventDefault();const value=$('#note-text').value.trim();if(!value){$('#note-status').textContent='Write something you want to keep, or carry on exploring.';return;}state.notes.unshift({id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),kind:$('#note-kind').value,text:value});state.draft='';$('#note-text').value='';save();notebook();$('#note-status').textContent=persistent?'Saved to your notebook.':'Kept here for this session. Copy your note before leaving.';});
try{const response=await fetch('../content/personal-study/recommendations.json');if(!response.ok)throw Error();items=await response.json();load();$('#note-text').value=state.draft;$('#featured').innerHTML=items.filter(a=>a.featured).map(a=>card(a,true)).join('');$('#gateways').innerHTML=gateways();$('#interests').innerHTML=Object.entries(interests).map(([id,label])=>`<button data-interest="${id}" aria-pressed="${id===filter}">${label}</button>`).join('');browse();notebook();if(location.hash.startsWith('#item-'))goTo(location.hash.slice(6),false);}catch{$('#featured').innerHTML='<p>The collection could not load. <a href="./">Try reloading this page</a>. Your saved notebook has not been changed.</p>';$('#note-form').hidden=true;$('#storage-status').textContent='The collection needs to load before your saved notebook can be shown.';}
