import {luxury as C} from './luxury-content.js';
export const luxuryTasks=C.tasks;
export const luxuryStages=[
 {id:'ferrari-summary',group:11,title:C.ferrari.title,kind:'task',data:'ferrari'},
 {id:'ferrari-nuance',group:11,title:'Are they still saying the same thing?',kind:'nuance',data:'ferrari'},
 {id:'ferrari-bridge',group:11,title:'From cars to perfume',kind:'bridge',data:'ferrari'},
 {id:'amouage-scan',group:12,title:C.amouage.title,kind:'task',data:'amouage'},
 {id:'amouage-summary',group:12,title:'Difficult language. An understandable idea.',kind:'task',data:'amouage'},
 {id:'amouage-tfng',group:12,title:'Task 1 · TRUE / FALSE / NOT GIVEN',kind:'task',data:'amouage'},
 {id:'amouage-completion',group:12,title:'Task 2 · Sentence completion',kind:'task',data:'amouage'},
 {id:'amouage-endings',group:12,title:'Task 3 · Matching sentence endings',kind:'task',data:'amouage'}
];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const p=s=>`<p>${esc(s)}</p>`;
const dict=s=>s&&typeof s==='object'&&!Array.isArray(s)?s:{};
const normalise=s=>String(s).trim().toLowerCase().replace(/\s+/g,' ').replace(/[.!?]+$/,'');
export const wordCount=s=>String(s).trim().split(/\s+/).filter(Boolean).length;
export function isLuxuryCorrect(task,index,value){
 const item=task.items[index];
 if(task.kind==='completion'&&wordCount(value)>2)return false;
 return item.accepted?item.accepted.includes(normalise(value)):item.answer===value;
}
export function installLuxury({state,save,app}){
 state.luxury=dict(state.luxury);const S=state.luxury;
 for(const name of ['answers','checked','panes','positions','notes'])S[name]=dict(S[name]);
 for(const [id,value] of Object.entries(S.answers))if(typeof value!=='string')delete S.answers[id];
 for(const [id,value] of Object.entries(S.notes))if(typeof value!=='string')delete S.notes[id];
 for(const [id,value] of Object.entries(S.positions))if(typeof value!=='number'||!Number.isFinite(value)||value<0)delete S.positions[id];
 S.nuance=Number.isInteger(S.nuance)&&S.nuance>=0&&S.nuance<=3?S.nuance:0;
 const key=(task,i)=>task.id+'-'+i;
 const value=(task,i)=>S.answers[key(task,i)]||'';
 const details=(title,body)=>`<details class="help"><summary>${esc(title)}</summary><div>${body}</div></details>`;
 function passage(data){return data.paragraphs.map((text,i)=>`<section class="c-paragraph" data-l-paragraph-text="${i}"><h3>Paragraph ${String.fromCharCode(65+i)}</h3><div class="passage">${p(text)}</div></section>`).join('');}
 function comparison(stage,body){const data=C[stage.data],pane=S.panes[stage.id]==='task'?'task':'passage';return `<p class="caption c-desktop-hint">Scroll the passage and questions separately to keep your place.</p><p class="caption c-phone-hint">Switch between passage and questions below. Each panel keeps your place as you scroll.</p><div class="c-mobile-tabs" role="group" aria-label="Compare the passage and task"><button data-l-pane="passage" aria-pressed="${pane==='passage'}">Read passage</button><button data-l-pane="task" aria-pressed="${pane==='task'}">Questions & support</button></div><div class="c-workbench" data-c-view="${pane}"><section class="c-pane c-passage-pane" data-l-scroll="passage" tabindex="0" role="region" aria-label="Complete ${stage.data==='ferrari'?'Ferrari':'Amouage'} passage"><div class="c-passage-tools"><span>Go to paragraph</span>${data.paragraphs.map((_,i)=>`<button class="secondary" data-l-paragraph="${i}" aria-label="Read paragraph ${String.fromCharCode(65+i)}">${String.fromCharCode(65+i)}</button>`).join('')}</div>${passage(data)}</section><section class="c-pane c-task-pane" data-l-scroll="task" tabindex="0" role="region" aria-label="${esc(stage.title)} questions and support">${body}</section></div>`;}
 function question(task,i){const item=task.items[i],id=key(task,i),picked=value(task,i);
  if(item.accepted)return `<div class="c-item"><label for="${id}">${esc(item.prompt)}</label><input id="${id}" name="${id}" type="text" autocomplete="off" spellcheck="false" data-l-task="${task.id}" data-l-index="${i}" value="${esc(picked)}" ${task.kind==='completion'?`aria-describedby="limit-${id}"`:''}>${task.kind==='completion'?`<p class="caption" id="limit-${id}">No more than two words · <span data-l-count="${id}">${wordCount(picked)}</span> entered</p>`:''}<button class="secondary c-unsure" type="button" data-l-unsure="${id}">Not sure yet</button></div>`;
  if(task.kind==='summary')return `<fieldset class="c-item"><legend>${esc(item.prompt)}</legend><div class="options">${item.options.map(o=>`<label class="option"><input type="radio" name="${id}" data-l-task="${task.id}" data-l-index="${i}" value="${o.value}" ${picked===o.value?'checked':''}><span>${o.value}. ${esc(o.text)}</span></label>`).join('')}</div></fieldset>`;
  return `<div class="c-item"><label for="${id}">${esc(item.prompt)}</label><select id="${id}" name="${id}" data-l-task="${task.id}" data-l-index="${i}"><option value="">Choose an answer</option>${item.options.map(o=>`<option value="${o.value}" ${picked===o.value?'selected':''}>${task.kind==='endings'?o.value+'. ':''}${esc(o.text)}</option>`).join('')}<option value="?" ${picked==='?'?'selected':''}>Not sure yet</option></select>${task.kind==='endings'?`<p class="c-selected-meaning" id="meaning-${id}">${esc(item.options.find(o=>o.value===picked)?.text||'')}</p>`:''}</div>`;
 }
 function results(task){const checked=S.checked[task.id]===true;return `<section class="c-results" id="results-${task.id}" ${checked?'':'hidden'} aria-label="Answers and explanations"><p class="c-result-summary" role="status">${checked?`${task.items.filter((_,i)=>isLuxuryCorrect(task,i,value(task,i))).length} / ${task.items.length} answers match. Compare the evidence below.`:''}</p>${checked?task.items.map((item,i)=>`<article class="c-result"><h3>${esc(item.prompt)}</h3><p><strong>${isLuxuryCorrect(task,i,value(task,i))?'That fits the text.':'Compare your answer.'}</strong> Answer: ${esc(item.answer)}${task.kind==='summary'||task.kind==='endings'?' — '+esc(item.options.find(o=>o.value===item.answer).text):''}</p>${task.kind==='completion'&&wordCount(value(task,i))>2?p('Your answer exceeds the two-word limit. Choose no more than two words from the passage.'):''}${details('Show evidence and reasoning',`<blockquote>${esc(item.evidence)}</blockquote>${p(item.rationale)}`)}</article>`).join(''):''}</section>`;}
 function taskBody(task){return `<form class="c-task" data-l-form="${task.id}" novalidate><h2>${esc(task.title)}</h2>${p(task.instruction)}${task.kind==='endings'?details('Endings A–G · keep nearby',`<ol class="l-endings" type="A">${task.endings.map(o=>`<li>${esc(o.text)}</li>`).join('')}</ol>`):''}${task.items.map((_,i)=>question(task,i)).join('')}<p class="caption">Attempt the complete set before checking. You can always continue and return later.</p><button type="submit" data-l-check="${task.id}">Check answers</button><p class="c-check-notice" role="status"></p>${results(task)}${task.id==='amouage-endings'?p('This is the last task in this continuation. You can revisit any stage using the workshop menu.'):''}</form>`;}
 function nuance(){const i=S.nuance;return `<h2>What changes when a limit disappears?</h2>${p('Read each version. Before moving on, ask: are they still saying the same thing?')}<p class="caption">Version ${i+1} of 4</p><blockquote class="l-nuance-claim" aria-live="polite">${esc(C.ferrari.nuance[i])}</blockquote><label for="l-notice">What changed? · optional</label><textarea id="l-notice" data-l-note="nuance" placeholder="Which limits have disappeared?">${esc(S.notes.nuance||'')}</textarea><div class="tool-actions"><button class="secondary" data-l-nuance="-1" ${i===0?'disabled':''}>← Previous version</button><button class="secondary" data-l-nuance="1" ${i===3?'disabled':''}>Next version →</button></div>${i===3?details('Compare what happened',`<p>The exaggerated claim did not appear from nowhere. It developed from something partly true.</p><ol>${C.ferrari.nuance.map(t=>`<li>${esc(t)}</li>`).join('')}</ol><p>First “some” disappears; then “particularly exclusive” disappears. Finally, a restriction on particular products becomes a broad claim about who may buy Ferrari cars.</p><p>Watch the scope of the claim and how certain it sounds. Paragraph B does not say that Ferrari personally selects every owner.</p>`):''}`;}
 function body(stage){if(stage.kind==='task')return comparison(stage,taskBody(C.tasks[stage.id]));if(stage.kind==='nuance')return comparison(stage,nuance());return `<blockquote>${esc(C.ferrari.bridge)}</blockquote>${p('Consider the question before opening the possibilities.')}<label for="l-bridge">My idea · optional</label><textarea id="l-bridge" data-l-note="bridge">${esc(S.notes.bridge||'')}</textarea>${details('What might contribute to niche luxury?',`<ul>${C.ferrari.bridgeIdeas.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><p>These features may contribute to value for some customers. They do not mean that everyone must like the product.</p>`)}<p>Continue to Amouage. Begin by scanning for a few facts; you do not need to understand every sentence at once.</p>`;}
 function render(stage){return `<div class="continuation luxury" data-l-screen="${stage.id}">${body(stage)}</div>`;}
 let timer;
 function remember(){const root=app.querySelector('.luxury');root?.querySelectorAll('[data-l-scroll]').forEach(el=>{if(el.getClientRects().length)S.positions[root.dataset.lScreen+'-'+el.dataset.lScroll]=el.scrollTop;});}
 function afterRender(){const root=app.querySelector('.luxury');if(!root)return;root.querySelectorAll('[data-l-scroll]').forEach(el=>{if(el.getClientRects().length)el.scrollTop=S.positions[root.dataset.lScreen+'-'+el.dataset.lScroll]||0;el.addEventListener('scroll',()=>{if(!el.getClientRects().length)return;S.positions[root.dataset.lScreen+'-'+el.dataset.lScroll]=el.scrollTop;clearTimeout(timer);timer=setTimeout(save,150);},{passive:true});});}
 function refresh(selector){remember();const root=app.querySelector('.luxury'),stage=luxuryStages.find(s=>s.id===root?.dataset.lScreen);if(!stage)return;root.outerHTML=render(stage);afterRender();if(selector)app.querySelector(selector)?.focus({preventScroll:true});save();}
 function change(el){const task=C.tasks[el.dataset.lTask],i=Number(el.dataset.lIndex);if(!task||!task.items[i])return;S.answers[key(task,i)]=el.value;S.checked[task.id]=false;const result=app.querySelector('#results-'+task.id);if(result){result.hidden=true;result.innerHTML='';}const notice=app.querySelector('.luxury .c-check-notice');if(notice)notice.textContent='';const count=app.querySelector(`[data-l-count="${key(task,i)}"]`);if(count)count.textContent=wordCount(el.value);const meaning=app.querySelector('#meaning-'+key(task,i));if(meaning)meaning.textContent=task.items[i].options.find(o=>o.value===el.value)?.text||'';save();}
 app.addEventListener('input',e=>{if(e.target.dataset.lTask&&e.target.type==='text')change(e.target);if(e.target.dataset.lNote){S.notes[e.target.dataset.lNote]=e.target.value;save();}});
 app.addEventListener('change',e=>{if(e.target.dataset.lTask)change(e.target);});
 app.addEventListener('submit',e=>{const task=C.tasks[e.target.dataset.lForm];if(!task)return;e.preventDefault();const missing=task.items.filter((_,i)=>!value(task,i).trim()).length;if(missing){e.target.querySelector('.c-check-notice').textContent=`Attempt all ${task.items.length} items before checking (${missing} left). You can continue and return later.`;return;}S.checked[task.id]=true;refresh(`[data-l-check="${task.id}"]`);app.querySelector('#results-'+task.id).scrollIntoView({block:'nearest',behavior:'instant'});});
 app.addEventListener('click',e=>{const b=e.target.closest('button'),root=b?.closest('.luxury');if(!root)return;
  if(b.dataset.lPane){remember();S.panes[root.dataset.lScreen]=b.dataset.lPane;root.querySelector('.c-workbench').dataset.cView=b.dataset.lPane;root.querySelectorAll('[data-l-pane]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.lPane===b.dataset.lPane)));const pane=root.querySelector(`[data-l-scroll="${b.dataset.lPane}"]`);pane.scrollTop=S.positions[root.dataset.lScreen+'-'+b.dataset.lPane]||0;save();}
  if(b.dataset.lParagraph!==undefined){const pane=root.querySelector('.c-passage-pane'),target=pane.querySelector(`[data-l-paragraph-text="${b.dataset.lParagraph}"]`);pane.scrollTop+=target.getBoundingClientRect().top-pane.getBoundingClientRect().top-12;remember();save();}
  if(b.dataset.lUnsure){const input=root.querySelector('#'+b.dataset.lUnsure);input.value='Not sure';change(input);}
  if(b.dataset.lNuance){S.nuance=Math.max(0,Math.min(3,S.nuance+Number(b.dataset.lNuance)));refresh(`[data-l-nuance="${S.nuance===3?-1:1}"]`);}
 });
 window.addEventListener('pagehide',()=>{remember();save();});
 return {screens:luxuryStages.map(s=>({id:s.id,title:s.title,group:s.group,body:()=>render(s)})),afterRender,remember};
}
